### ISSUE TITLE
No module named 'win32api'

### ISSUE THREAD

**Issue by ItzMUSH69** [tryptech/obs-zoom-and-follow#103]
I am running Windows 10, python 3.10.10 and have installed pwc

```
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "D:\OBS extents/Scripts/obs-zoom-and-follow-master\zoom_and_follow_mouse.py", line 11, in <module>
[zoom_and_follow_mouse.py]     import pywinctl as pwc
[zoom_and_follow_mouse.py]   File "C:\Users\bhanu\AppData\Local\Programs\Python\Python310\lib\site-packages\pywinctl\__init__.py", line 673, in <module>
[zoom_and_follow_mouse.py]     from ._pywinctl_win import (
[zoom_and_follow_mouse.py]   File "C:\Users\bhanu\AppData\Local\Programs\Python\Python310\lib\site-packages\pywinctl\_pywinctl_win.py", line 13, in <module>
[zoom_and_follow_mouse.py]     import win32api
[zoom_and_follow_mouse.py] ModuleNotFoundError: No module named 'win32api'
```

**Comment by Kalmat** [comment]
Hi!

Please, try this:

`python3 -m pip install pywinctl==0.0.38 --force-reinstall`

and let me know if it works.

**Comment by RuneMason1** [comment]
Same problem. Also, python3 doesn't work, but python does
I have python 310 installed

**Comment by Kalmat** [comment]
The most common and cross-platform way of invoking Python 3 is `python3` command, but specially in windows, it depends on how Python was installed (from MS-Store or with a installer), if it has been added to the system PATH, if there are one or more python versions installed, etc. In windows, it's also common to invoke it as `py` or `py -3`. Take a look at [this](https://stackoverflow.com/questions/7054424/python-not-recognized-as-a-command), as an example to diagnose and solve your issue.

**Comment by RuneMason1** [comment]
So even though we choose a python installation directory in OBS, it still needs to be in windows environment variables in order to run properly?

**Comment by Kalmat** [comment]
Sorry, but I'm not an OBS expert. Just guessing, perhaps the Python path in OBS is wrong?

I found [this](https://www.reddit.com/r/obs/comments/10y56ok/having_trouble_getting_python_working_in_obs_on/) in reddit, which may be useful (see Cuboidiots' answer on OBS/Python versions and OBS paths).

**Comment by DureSabih** [comment]
none of aobve worked for me . using windows 11 with python 3.6.8

**Comment by danielsjdr** [comment]
Same issue in Python 3.11

[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:\Program Files/obs-studio/data/obs-plugins/frontend-tools/scripts\zoom_and_follow_mouse.py", line 17, in <module>
[zoom_and_follow_mouse.py]     import pywinctl as pwc
[zoom_and_follow_mouse.py]   File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\site-packages\pywinctl\__init__.py", line 797, in <module>
[zoom_and_follow_mouse.py]     from ._pywinctl_win import (Win32Window as Window, checkPermissions, getActiveWindow, getActiveWindowTitle,
[zoom_and_follow_mouse.py]   File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\site-packages\pywinctl\_pywinctl_win.py", line 26, in <module>
[zoom_and_follow_mouse.py]     import win32api
[zoom_and_follow_mouse.py] ModuleNotFoundError: No module named 'win32api'

I've been thought all ideas in all places around internet and nothing solved it

**Comment by tryptech** [comment]
Closing as python installation errors are out of scope for support.
