### ISSUE TITLE
KeyError: 'monitor' (dual monitor)

### ISSUE THREAD

**Issue by Spectrumnist** [tryptech/obs-zoom-and-follow#105]
**Preface:**
I say dual monitor because I've made this work in the past by mirroring my cursor movements using Input Director, and yes, it _did_ work for a good while. As long as I disabled the cursor mirroring after exiting a zoom, it technically worked.

**Error:**
```[zoom_and_follow_mouse.py] {}
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "D:\OBS PYTHON\zoom_and_follow_mouse.py", line 371, in toggle_zoom
[zoom_and_follow_mouse.py]     zoom.update_source_size()
[zoom_and_follow_mouse.py]   File "D:\OBS PYTHON\zoom_and_follow_mouse.py", line 66, in update_source_size
[zoom_and_follow_mouse.py]     data = loads(data)['monitor']
[zoom_and_follow_mouse.py] KeyError: 'monitor'
```
**Specs:**
_Gaming Monitor on Gaming PC:_ 2560 x 1440
_Samsung TV on Streaming PC:_ 3840 x 2160
_OBS Version:_ 27.2.4 (64-bit) [https://github.com/obsproject/obs-studio/releases/tag/27.2.4](url)
_Python Version:_ Mushiiies Python Portable [https://github.com/Mushiiies/OBS-PYTHON](url)

**Description:**
- Using my StreamDeck, I tell SAMMI Core to trigger the OBS Hotkey named "zoom.toggle" 
- Not sure where exactly "zoom.toggle" came from, must've been found somewhere in the OBS scene .json file
- This setup has worked in the past to trigger zoom_and_follow_mouse.py and stopped working months ago
- When I use this now, there is no zoom, however, using Mushiiies Python Portable still loads the script description/settings in OBS
- If there's a way to get zoom_and_follow_mouse.py to work on my Streaming PC's monitor, then I can do the rest to get it to work for my dual PC setup using Input Director to mirror my cursor
- My ideal setup would be a way to toggle a button on my Gaming PC that started the mirroring process (capturing only cursor movements and not inputs so I don't accidentally close programs on my Streaming PC) and have that button activate zoom and follow. My current setup is close to that, but Input Director doesn't allow me to disable mouse input on one machine and allow input on another, but I make do.

**Comment by chuthehuan** [comment]
i use portable python 3.6 with 28.1.2 and it works well. Both display capture and window capture. You should give it a try!

**Comment by Spectrumnist** [comment]
I've considered moving up to 28.1.2, but I have several plugins and scripts and I'm not sure which ones will break if/when I update OBS.

**Comment by chuthehuan** [comment]
just try to use [OBS-Studio-28.1.2-Full-x64.zip](https://github.com/obsproject/obs-studio/releases/download/28.1.2/OBS-Studio-28.1.2-Full-x64.zip), old preferences and scripts are preserved.

**Comment by REALtony4twenty** [comment]
me and another user in discord are trying to get the latest version possible for OBS 29. I now have it working. Was getting the same monitor issue but seemed to be fixed when I updated everything when these settings appeared in the script settings

![image](https://github.com/tryptech/obs-zoom-and-follow/assets/101494591/1cae6950-191d-41d1-aa5b-12427ab70f88)

**Comment by tryptech** [comment]
Closing as old versions of python/OBS/script are out of scope for support. If this is still an issue, please reproduce and resubmit with current working versions of python, OBS, script and dependencies.
