### ISSUE TITLE
Unable to change zoom location, log shows mouse position changing

### ISSUE THREAD

**Issue by time2innov8** [tryptech/obs-zoom-and-follow#106]
I have successfully installed the script on two laptops and also used version 28 and 29 of OBS however I get the same issue on both systems. In all the tutorials I have seen for the script it is the zoom value being changed that alters the window size. However changing that value makes no difference. The only way I can zoom in to a defined box size is adjusting the manual monitor size. If I leave everything at default when triggered it zooms into a 1 pixel wide and high area of the top left corner. Although I can zoom changing the monitor size it still only shows the top left hand corner, in the script log I can see the value changing to show the mouse movement is being tracked. The follow mouse function does not do anything at all. Is there a list of steps I can take to resolve the issue, it is being run on a laptop with no external display.

**Comment by tryptech** [comment]
Multimonitor support was recently refactored as of 2023-09-11. If this is still an issue, please reproduce and resubmit with current working versions of python, OBS, script and dependencies.
