### ISSUE TITLE
cant see the properties

### ISSUE THREAD

**Issue by hardlevel** [tryptech/obs-zoom-and-follow#107]
Hi, I was following the guide to make it work, but after added the script on obs, it appears on the list, but there's no settings there

I installed the most updated version of python 3.11 and added the folder on the scripts option

I'm missing something? Thanks!

**Comment by LQTliquite** [comment]
use this.
https://github.com/Mushiiies/OBS-PYTHON

**Comment by hardlevel** [comment]
> 

thanks! it solved the problem!
