### ISSUE TITLE
Issue with 2 scripts running.

### ISSUE THREAD

**Issue by Keanomy** [tryptech/obs-zoom-and-follow#112]
Hello,

I'm having some issues with my second file.
I have copied and made 2 script files:
Destop.py
GameZoom.py

OBS 29.1.1
Script version = "v.2023.04.16"
Python 3.11

Desktop.py works as intended with the source I've selected.
However the GameZoom is added to a game capture source but does not function consistently.
When hitting the hotkey to Zoom in the game capture source is changed to a 1x1 pixel transform. 
![obs64_m7OKD1A30b](https://github.com/tryptech/obs-zoom-and-follow/assets/8218911/d030f43e-862f-41f8-8400-5547848ecdf4)

I have also notice that the ZoomCrop filter added displays 0,0,0,0 as value.
![obs64_rFgxOqWsQN](https://github.com/tryptech/obs-zoom-and-follow/assets/8218911/4a179a20-9d5a-4d21-8862-8654749b9ba9)

When I hit the button to revert the Zoom the source goes away completely and the ZoomCrop filter goes to values -1280,-720,1280,720.

This only happens to the second script I add.

Here is the script log as well:
[py log.txt](https://github.com/tryptech/obs-zoom-and-follow/files/11453826/py.log.txt)

Feel free to reach out on discord if preferred: Keanomy#5973

**Comment by tryptech** [comment]
Multiscript support was recently refactored as of 2023-09-11. If this is still an issue, please reproduce and resubmit with current working versions of python, OBS, script and dependencies.
