### ISSUE TITLE
Problem with 4k display when I record on FHD

### ISSUE THREAD

**Issue by sokart** [tryptech/obs-zoom-and-follow#113]
Great work in this repository. I have the following issue:
**Setup:** MacBook pro (1680x1050 res) connected to a 4K monitor (3840x2160) and I am using OBS to record a video in 1920x1080.
**Problem/Ask:** I have added an Screen Capture to the external 4k display. I have configured both the script parameters and transform based on the instructions. However the zoom and follow works only for the 1/4 of the 4k display. Could you let me know if this is a problem of the script or to suggest the optimal configuration?

Thank you in advance

**Comment by tryptech** [comment]
This was likely do to how Macs do HiDPI, HiDPI support was recently refactored as of 2023-09-11. If this is still an issue, please reproduce and resubmit with current working versions of python, OBS, script and dependencies.
