### ISSUE TITLE
Zoom window Width and Height reset everytime OBS restarts

### ISSUE THREAD

**Issue by joaolimapiano** [tryptech/obs-zoom-and-follow#116]
Hello. It's my first time reporting an issue, I'm sorry if there's missing information. Every time I restart OBS, the zoom changes width and height. It doesn't change the values written in the scripts window, but clearly the zoom is smaller. I have the zoom set to 640 by 360. It should be pretty close, and when I restart OBS, it isn't. 

A manual fix has been changing the width and height to something else and then changing it again to 640 by 360. But I have to do that every time I wan't to use it. 

I'm using v.2023.05.16. My python version is 3.10. 

Thank you for reading!

**Comment by tryptech** [comment]
Settings saving and loading was recently refactored as of 2023-09-11. If this is still an issue, please reproduce and resubmit with current working versions of python, OBS, script and dependencies.
