### ISSUE TITLE
not working with wide screen

### ISSUE THREAD

**Issue by Username69992872** [tryptech/obs-zoom-and-follow#117]
I got a 5120x1440 Widescreen Monitor. I want it to work with a Window which is 2560x1440 on the right half of the screen. 
Whatever I set, it just does not work. Expecially it somehow resets the Source Crop Filter to width 0 height 0 always. No Idea why.

**Comment by Username69992872** [comment]
hello? anyone there ?

**Comment by tryptech** [comment]
Duplicate of #90. Closing.
