### ISSUE TITLE
Not maintaining monitor override setting between OBS restarts

### ISSUE THREAD

**Issue by thelegendtubaguy** [tryptech/obs-zoom-and-follow#118]
This is how I have the script configured and working.
![image](https://github.com/tryptech/obs-zoom-and-follow/assets/95944177/a3678cf5-cf9c-4528-9f34-219e47c0862c)

But when I close OBS and reopen, it looks like this:
![image](https://github.com/tryptech/obs-zoom-and-follow/assets/95944177/723c8605-0a6e-4a9b-8518-55b1ff7e82cb)

I'm having to reconfigure the monitor override value every time I open OBS.

**Comment by GamingWithShaurya** [comment]
im having the same issue, and also if i recorded/streamed on that obs session
then if i exit obs after its all done, then it gives me a crash log for some reason

**Comment by tryptech** [comment]
Settings saving and loading was recently refactored as of 2023-09-11. If this is still an issue, please reproduce and resubmit with current working versions of python, OBS, script and dependencies.
