### ISSUE TITLE
OBS crashes on exit when using this script

### ISSUE THREAD

**Issue by thelegendtubaguy** [tryptech/obs-zoom-and-follow#119]
Running Python 3.11, as soon as I add this script I get a crash every time I exit OBS.  I can provide more of the thread dump if you like.

```
Unhandled exception: c0000005
Date/Time: 2023-06-24, 05:49:00
Fault address: 7FFE7B586F3F (c:\users\tuba\documents\streamsync\stream apps profiles\obs-studio\bin\64bit\obs.dll)
libobs version: 29.1.2 (64-bit)
Windows version: 10.0 build 22621 (release: 22H2; revision: 1848; 64-bit)
CPU: AMD Ryzen Threadripper PRO 3975WX 32-Cores     


Thread 74E8: tiny_tubular_task_thread (Crashed)
Stack            EIP              Arg0             Arg1             Arg2             Arg3             Address
00000003C5CFF6D0 00007FFE7B586F3F 000001EC0736DA70 0000000000000001 000001EC0742EEA0 0000000000000001 obs.dll!obs_source_get_signal_handler+0x2f
00000003C5CFF700 00007FFE7B57D05A 0000000000000001 0000000000000001 0000000000000000 0000000000000000 obs.dll!obs_sceneitem_release+0x6a
00000003C5CFF730 00007FFE7B57E43D 000001EC0742EEA0 000001EBFBED0308 000001EBFBED0300 000001EBFBED02E0 obs.dll!remove_all_items+0x1bd
00000003C5CFF790 00007FFE7B5788DE 0000000300000000 00007FFE7B5D6E18 00000003C5CFF7E8 000001EC05B26BA0 obs.dll!scene_destroy+0xe
00000003C5CFF7C0 00007FFE7B584D8C 000001EBE8FA4460 000001EBE8FA4460 000001EC217E4500 0000000000000400 obs.dll!obs_source_destroy_defer+0xcc
00000003C5CFF8C0 00007FFE7B5C592E 00000003C5CFF969 0000000000000000 0000000000000000 0000000000000000 obs.dll!tiny_tubular_task_thread+0x3ee
00000003C5CFF920 00007FFECC7F78B6 000001EBE07CFAB0 0000000000000000 0000000000000000 0000000000000000 w32-pthreads.dll!ptw32_threadStart+0x126
00000003C5CFF9D0 00007FFED44C9363 0000000000000000 0000000000000000 0000000000000000 0000000000000000 ucrtbase.dll!0x7ffed44c9363
00000003C5CFFA00 00007FFED52B26AD 0000000000000000 0000000000000000 0000000000000000 0000000000000000 kernel32.dll!0x7ffed52b26ad
00000003C5CFFA30 00007FFED692A9F8 0000000000000000 0000000000000000 0000000000000000 0000000000000000 ntdll.dll!0x7ffed692a9f8
```

**Comment by tryptech** [comment]
I think this was the same issue as #124. Can you reproduce the issue on the most recent version?

**Comment by MathieuCGit** [comment]
Hello, I can reproduce this with OBS  29.1.3 and last version of your script. Let me know if you want more informations :)

**Comment by adjstreams** [comment]
@thelegendtubaguy and @MathieuCGit other than this script what other plugins do you have installed?

**Comment by daeavelwyn** [comment]
@adjstreams : I have no other plugins...

**Comment by MathieuCGit** [comment]
Hello @adjstreams ,

I'm using lower-third plugin (https://obsproject.com/forum/resources/animated-lower-thirds-with-dockable-control-panel.1057/) which as nothing to deal with python, and that's it.

I've tried to disable this plugin but got the same crash result. Disabling obs-zoom-and-follow and OBS no more crashes. 

Let me know if you want more informations :)

regards

**Comment by thelegendtubaguy** [comment]
Updating to the latest version of this script and OBS 30 RC 2 fixed this for me (I did both at the same time for reasons...  not ideal I know).

Since I opened this, I'm going to close it.  If others are still having issues, you need to post logs snippets and make 100% sure you're using at least python 3.11, have pip installed the required python modules, and are using the latest version of the script that's available.  Also make sure to go in and reset all of your settings on the script to what you want.

**Comment by MathieuCGit** [comment]
Hello,

Regarding @thelegendtubaguy message I made deeper tests and it seems you do not need to update OBS to 30 RC2 but you have to update python to 3.11.6. In my case this simple update resolve the problem.

Be carefull that updading python is not really clean by itself. I also had to remove "python310" from my environment path, see [https://geekflare.com/system-environment-variables-in-windows/](https://geekflare.com/system-environment-variables-in-windows/) to clean your path env

Thanks @thelegendtubaguy to point this python update workaround :)
