### ISSUE TITLE
Error when loading script

### ISSUE THREAD

**Issue by WickedJynx** [tryptech/obs-zoom-and-follow#120]
I am having this issue when trying to add the script to obs

[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:/Program Files/obs-studio/data/obs-plugins/frontend-tools/scripts\zoom_and_follow_mouse.py", line 14, in <module>
[zoom_and_follow_mouse.py]     import pywinctl as pwc
[zoom_and_follow_mouse.py]   File "C:\Users\pikah\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinctl\__init__.py", line 4
[zoom_and_follow_mouse.py]     from __future__ import annotations
[zoom_and_follow_mouse.py]     ^
[zoom_and_follow_mouse.py] SyntaxError: future feature annotations is not defined

**Comment by DureSabih** [comment]
I'm having the same issue. did you figure out how to fix it?

**Comment by VideoFX** [comment]
Same error here.

[zoom_and_follow_mouse.py] SyntaxError: future feature annotations is not defined

**Comment by jonlittle514** [comment]
Same issue, i need help pls.

**Comment by tryptech** [comment]
You are using a version of python <3.7. future annotations was introduced as of python 3.7. As stated in the project description, this script was built using python 3.10. Closing as python installation errors are out of scope for support.

**Comment by jonlittle514** [comment]
i fixed it by downloading an older version of pywinctl (Pywinctl 0.0.38)
