### ISSUE TITLE
Zoom Options in OBS Not showing

### ISSUE THREAD

**Issue by hunt0777** [tryptech/obs-zoom-and-follow#128]
The video shows I am supposed to see.. https://nimb.ws/XZEbPk the options.
But I don't.. see, all I see is... https://nimb.ws/dcELhb, "No properties available"

Below is the script log...

Can you help?

[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py] File "C:/Program Files/obs-studio/data/obs-plugins/frontend-tools/scripts\zoom_and_follow_mouse.py", line 14, in
[zoom_and_follow_mouse.py] import pywinctl as pwc
[zoom_and_follow_mouse.py] File "C:\Users\Craig\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinctl_init_.py", line 27, in
[zoom_and_follow_mouse.py] from .main import (Re, Window, checkPermissions, getActiveWindow,
[zoom_and_follow_mouse.py] File "C:\Users\Craig\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinctl_main.py", line 3
[zoom_and_follow_mouse.py] from future import annotations
[zoom_and_follow_mouse.py] ^
[zoom_and_follow_mouse.py] SyntaxError: future feature annotations is not defined
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py] File "C:/Program Files/obs-studio/data/obs-plugins/frontend-tools/scripts\zoom_and_follow_mouse.py", line 14, in
[zoom_and_follow_mouse.py] import pywinctl as pwc
[zoom_and_follow_mouse.py] File "C:\Users\Craig\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinctl_init.py", line 27, in
[zoom_and_follow_mouse.py] from ._main import (Re, Window, checkPermissions, getActiveWindow,
[zoom_and_follow_mouse.py] File "C:\Users\Craig\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinctl_main.py", line 3
[zoom_and_follow_mouse.py] from future import annotations
[zoom_and_follow_mouse.py] ^
[zoom_and_follow_mouse.py] SyntaxError: future feature annotations is not defined

**Comment by tryptech** [comment]
You're using Python 3.6, the script is written under Python 3.10. future feature annotations was added in in Python 3.7 so it will not work under the current version of Python you have installed.

Closing as old versions of Python/OBS/script are out of scope for support. If this is still an issue, please reproduce and resubmit with current working versions of Python, OBS, script and dependencies.
