### ISSUE TITLE
OBS does not recognize the script

### ISSUE THREAD

**Issue by LiveDoEdu** [tryptech/obs-zoom-and-follow#15]
After installing the pip, the script does not appear. No properties available.

![obs64_vLjCtOpe6M](https://user-images.githubusercontent.com/82877143/115381071-98cc4180-a1a9-11eb-9dcc-f76c90c6a1ad.png)

**Comment by mrgomides** [comment]
i have the same problem

**Comment by night-stand** [comment]
does version have to be 3.6, or can i use a later version, such as 3.9?  cuz, i've done all the net has told me to do...and still no properties...  :/

**Comment by lholenstein** [comment]
Python version 3.6 is only getting security patches now and will go out of support soon-ish. I'd love to see this updated to work with 3.9 as well.

**Comment by tryptech** [comment]
It's predominantly a limitation with OBS on Windows as found here: https://obsproject.com/docs/scripting.html
My primary use case is with a Windows machine so the plugin is developed as such.

If someone wants to maintain a 3.9 version (if OBS on other platforms supports it) then by all means, please do so. The more accessibility the better.

**Comment by tryptech** [comment]
Closing since the script has refactored and dependencies have changed. If the issue comes up again, please create a new issue.
