### ISSUE TITLE
Won't follow mouse in a different Monitor

### ISSUE THREAD

**Issue by astronaut954** [tryptech/obs-zoom-and-follow#19]
I have 2 monitors, one is 1920 x 1080, setted in source "Monitor [Capture]", and the other one is 1280 x 800, setted in source "TV [Capture]. I've created 2 different scripts for each one of the monitors ("zoom_and_follow_mouse_1.py" and "zoom_and_follow_mouse_2.py") so I can use the zoom in both of them, yet in the second monitor it just won't work. Even that it will zoom in the right source, "TV [Capture]", the zoom will follow my mouse in the 1920 x 1080 monitor and not in the 1280 x 800 monitor as intended even choosing \\. \DISPLAY2 it won't track in the right monitor.

**Comment by tatunts** [comment]
Hello! Have you found a solution for this? This is very important for my tutorials, I really need to use my secondary monitor... Thanks.

**Comment by astronaut954** [comment]
Hi @tatunts! No, I haven't found a solution to this problem, unfortunately. Yet I've noticed another issue: when I had 2 zoom scripts working simultaneously, my OBS would lag the entire computer, I haven't tested it a lot, but maybe it has something to do about the way the script was set. I'm not a programmer so I can't fix this problem, maybe we will have to wait for the developers to fix this issue or implement a new feature.

**Comment by tatunts** [comment]
Thanks for the reply!

**Comment by tryptech** [comment]
Should be corrected in newest commit.
