### ISSUE TITLE
funky behavior for retina 

### ISSUE THREAD

**Issue by cognitiaclaeves** [tryptech/obs-zoom-and-follow#20]
I have a 16-inch (3072 × 1920) with retina display.

When it auto detects, it appears to auto-detect the base canvas resolution as 3584x2240.
It also gave an output resolution that did not match the same aspect ratio. Since the above showed as 16:10, I manually changed the output to 1792x1120 (also 16:10).

Then I configured the script settings:
At this time, display source isn't auto-populating. But I found that I could just type in the video capture source I was using.
I don't recall there ever being anything in the drop-down for `select monitor to use base for zooming` except for `manual monitor size`.

I set the manual monitor width to 3584 and the height to 2240, and the zoom to 1280x768, respectively. The rest I leave at default. I set a hot-key for the zoom, and a different one to follow the mouse.

Then, when I press the zoom key, it zooms in. Pressing the key again zooms back out, filling the bounds again, as expected.

Editing the transform to position in center and stretch to the bounds shows some movement, but it looks like the cursor drops off the screen about 1/3 of the way across. It then becomes apparent that it wasn't following the cursor, exactly.

One other thing that I've noticed is that screeninfo is not returning the same dimensions reported by the about mac dialog, or that the auto-detect calculates:

```
>>> from screeninfo import get_monitors
>>> get_monitors()
[Monitor(x=0, y=0, width=1792, height=1120, width_mm=None, height_mm=None, name=None)]
```

I did try forcing the base canvas to match that height and width, but that didn't really seem to help.
I did determine that if I put in 3584x2240 for the ZoomCrop filter dimensions that it scaled back out to expected size. Until I hit the hot-key again.

... almost suggesting that the something about how the filter behaves is somehow unique.

... Any ideas? I'm pretty much out.

**Comment by cognitiaclaeves** [comment]
I 'fixed' this by adding a multiplier that gets applied to both width and height of the monitor data returned by screeninfo as well as the x,y coordinates that are returned by pynput.mouse.position . This seems very hackish, but a way to get the correct resolution didn't even seem to exist. At least this way, the user can visually figure that the dimensions that default with the script don't match the dimensions that the application sets, and make a calculation to determine if there's a multiple that works. In my case, it's 2 -- if I double everything, then it works like a charm.

**Comment by tryptech** [comment]
Currently I depend on the screeninfo library for any and all screen parameters. If that library gets Mac Retina scaling info I would adopt it.

I could theoretically just add a Retina toggle as well which just doubles the canvas size in the code function but like you said, I'd have to also test the scenario of a retina and non retina screen and how it affects the "combined" monitor convas.

**Comment by tryptech** [comment]
Closing since the script has refactored and dependencies have changed. It may account for Retina, but if the issue comes up again, please create a new issue.
