### ISSUE TITLE
Zoom in option

### ISSUE THREAD

**Issue by knkrth** [tryptech/obs-zoom-and-follow#21]
On the script setting, Can you add a option like 2x zoom, 5x zoom, 10x zoom Instead of entering the width & height manually. 

 It would nice to auto detect screen resolution & 2x zoom or so...

**Comment by tryptech** [comment]
In general most OBS canvases tend to be 16x9. I run a 21:9 monitor, and some people will run 32:9 or other odd aspect ratios. Some people may even run non-16:9 canvases. Leaving the setting to pixel dimensions to allow users to fine tune to their needs specifically.
