### ISSUE TITLE
Trigger from One Zoom Level to Another

### ISSUE THREAD

**Issue by brucerothwell** [tryptech/obs-zoom-and-follow#23]
I'd like to be able to start with, say a zoom level of 1280x720 (150%, based on a 1920x1080 screen), then instead of having to first toggle back up to 1920x180, before I can then use the separate hotkey for zooming to 960x540 (200%), then only being able to use THAT key to toggle to 100% (1920x1080).

Perhaps being able to assign a hotkey that simply toggles zoom, regardless of which level currently zoomed into.

Then a 2nd key that let's you toggle between different zoom levels. (I have seen other hotkeys behave such that if you assign the same keystroke for multiple actions, repeatedly pressing that hotkey switches from one to the other to the other.)

**Comment by tryptech** [comment]
I think that this "zooming in steps" functionality is a good idea, but a bit beyond my scope for now. I might revisit it in the future though.
