### ISSUE TITLE
here I did not get a Description, anything, what to try?

### ISSUE THREAD

**Issue by lse123** [tryptech/obs-zoom-and-follow#24]
https://youtu.be/i0_JXqiJBVc?t=307  << here I did not get a Description, anything, what to try?

**Comment by mrkshdt** [comment]
did you fix it?

**Comment by dakipro** [comment]
Same here on windows 10, OBS 27.1.3 and python 3.9
Any tips?

**Comment by tryptech** [comment]
With windows, OBS only supports up to python 3.6.8 for now. Please use that version and point OBS to 3.6.8 if the script does not load

**Comment by lse123** [comment]
Can have two Python 3.x versions in the same OS Windows 10...?

**Comment by tryptech** [comment]
You can, just make sure they are distinct 
![image](https://user-images.githubusercontent.com/654389/162268334-0fd7d05d-5039-4dac-a2ed-afc8e1a13050.png)

**Comment by lse123** [comment]
In OBS how do you choose python3.6 instead of 3.9...?
