### ISSUE TITLE
active border

### ISSUE THREAD

**Issue by amandabruh** [tryptech/obs-zoom-and-follow#27]
hi, i want the cursor to be ALWAYS in the center, even if it means i get black bars if i move my mouse to the corners of the monitor, is there anyway i can do that? (its necessary)

**Comment by tryptech** [comment]
I think I added it in https://github.com/tryptech/obs-zoom-and-follow/commit/68e1aef99cb2d55a60324e1ea9d48f92815f8949
If you set the active border to 0.5 it should keep the cursor centered and allow the zoom window to escape the monitor bounds.
