### ISSUE TITLE
Active Border above 0.16 causes flicker

### ISSUE THREAD

**Issue by bazz1tv** [tryptech/obs-zoom-and-follow#28]
Hello!! I have a 1080p OBS canvas, I use a 4K monitor scaled down. Everything working great, with this one caveat mentioned in the title.

Here are my Transform settings and here are my script settings below.

![{550AE9BA-97C1-44C8-8DE0-4CB976EE93A9}](https://user-images.githubusercontent.com/2224787/143777122-21fed7f9-1f8e-417d-918e-0ef964bdc734.png)
![{8F4D6149-FAA4-4667-893A-5F60DEF4A2A7}](https://user-images.githubusercontent.com/2224787/143777123-651401c7-b1a8-4921-aa3c-207b63ef4853.png)

There's no flicker when active border is set at 0.16 and lower. Also, when set above 0.16, there is no flicker if we are at a screen edge.

If there's anything else I can provide, I will be happy to.

**Comment by tryptech** [comment]
I think I've corrected it in https://github.com/tryptech/obs-zoom-and-follow/commit/68e1aef99cb2d55a60324e1ea9d48f92815f8949
If you could test and confirm
