### ISSUE TITLE
Getting this when using with Ubuntu 21.10

### ISSUE THREAD

**Issue by realwumbl3** [tryptech/obs-zoom-and-follow#29]
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "/home/wumbl3/Documents/obs-zoom-and-follow-master/zoom_and_follow_mouse.py", line 19, in <module>
[zoom_and_follow_mouse.py]     class CursorWindow:
[zoom_and_follow_mouse.py]   File "/home/wumbl3/Documents/obs-zoom-and-follow-master/zoom_and_follow_mouse.py", line 26, in CursorWindow
[zoom_and_follow_mouse.py]     d_w = get_monitors()[monitor_idx].width
[zoom_and_follow_mouse.py]   File "/home/wumbl3/.local/lib/python3.9/site-packages/screeninfo/screeninfo.py", line 32, in get_monitors
[zoom_and_follow_mouse.py]     raise ScreenInfoError("No enumerators available")
[zoom_and_follow_mouse.py] screeninfo.common.ScreenInfoError: No enumerators available

Any ideas?

**Comment by ahfauth** [comment]
Same on debian 12 (testing). I would love to use it on Linux!

Did you manage to fix it @realwumbl3 ?

**Comment by eribertomota** [comment]
+1, Debian 11 Stable.

```
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "/home/eriberto/obs-scripts/zoom_and_follow_mouse.py", line 19, in <module>
[zoom_and_follow_mouse.py]     class CursorWindow:
[zoom_and_follow_mouse.py]   File "/home/eriberto/obs-scripts/zoom_and_follow_mouse.py", line 26, in CursorWindow
[zoom_and_follow_mouse.py]     d_w = get_monitors()[monitor_idx].width
[zoom_and_follow_mouse.py]   File "/usr/lib/python3/dist-packages/screeninfo/screeninfo.py", line 37, in get_monitors
[zoom_and_follow_mouse.py]     raise ScreenInfoError("No enumerators available")
[zoom_and_follow_mouse.py] screeninfo.common.ScreenInfoError: No enumerators available
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "/home/eriberto/obs-scripts/zoom_and_follow_mouse.py", line 19, in <module>
[zoom_and_follow_mouse.py]     class CursorWindow:
[zoom_and_follow_mouse.py]   File "/home/eriberto/obs-scripts/zoom_and_follow_mouse.py", line 26, in CursorWindow
[zoom_and_follow_mouse.py]     d_w = get_monitors()[monitor_idx].width
[zoom_and_follow_mouse.py]   File "/usr/lib/python3/dist-packages/screeninfo/screeninfo.py", line 37, in get_monitors
[zoom_and_follow_mouse.py]     raise ScreenInfoError("No enumerators available")
[zoom_and_follow_mouse.py] screeninfo.common.ScreenInfoError: No enumerators available
```

Thanks!

**Comment by tryptech** [comment]
From the error, the issue looks to be ScreenInfo not having an enumerator for whatever window manager is in use. I plan on refactoring to PyWinCtl soon for a few things. If it's window manager agnostic, it should fix the problem

**Comment by tryptech** [comment]
Closing since the script has refactored and dependencies have changed. If the issue comes up again, please create a new issue.
