### ISSUE TITLE
script on Linux openSUSE Tumbleweed

### ISSUE THREAD

**Issue by ivoermejo** [tryptech/obs-zoom-and-follow#33]
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "/usr/share/obs/obs-plugins/frontend-tools/scripts/obs-zoom-and-follow-master/zoom_and_follow_mouse.py", line 20, in <module>
[zoom_and_follow_mouse.py]     class CursorWindow:
[zoom_and_follow_mouse.py]   File "/usr/share/obs/obs-plugins/frontend-tools/scripts/obs-zoom-and-follow-master/zoom_and_follow_mouse.py", line 28, in CursorWindow
[zoom_and_follow_mouse.py]     monitors = pwc.getAllScreens()
[zoom_and_follow_mouse.py]   File "/home/ivo/.local/lib/python3.8/site-packages/pywinctl/_pywinctl_linux.py", line 881, in getAllScreens
[zoom_and_follow_mouse.py]     'workarea': Rect(crtc.x + wa[0], crtc.y + wa[1], crtc.x + crtc.width - (SCREEN.width_in_pixels - wa[2] - wa[0]), crtc.y + crtc.height - (SCREEN.height_in_pixels - wa[3] - wa[1])),
[zoom_and_follow_mouse.py] TypeError: 'NoneType' object is not subscriptable

**Comment by tryptech** [comment]
Could I get some more information about your specific OS and window manager? I think this is an issue with PyWinCTL, so I will bring it up there

**Comment by Kalmat** [comment]
Hi! It's crucial to know which config you are using (OS version, Desktop environment, etc.) in order to diagnose this issue. In addition to that, I found a "hidden" bug in LXDE which could be your case too. Please upgrade PyWinCtl module to version 0.0.34 (you can find the wheel file here: https://github.com/Kalmat/PyWinCtl/tree/master/dist

```
python3 -m pip uninstall pywinctl
python3 -m pip install PyWinCtl-0.0.34-py3-none-any.whl
```

**Comment by SanctusStreams** [comment]
i also am having issues installing this pywinclt. I use windows 10, and version 3.6.8 of python. I need it for the OBS mouse follow script. I am kinda stumped at the moment and already left my full information on the error in tryptech's convo/(thread) attached to this convo.

**Comment by tryptech** [comment]
@ivoermejo if Kalmat's update didn't solve the issue, please let me know and I'll reopen the issue.

@SanctusStreams Are you sure that OBS is using Python 3.6.8 specifically? A common issue people have is having multiple Python installations and not installing pywinctl to the right one, and not pointing OBS to the right version. Try making sure you install PyWinCtl to specifically Python 3.6.8, and make sure that Python Settings in the Scripts window is pointed at the 3.6.8 version of Python.

**Comment by Kalmat** [comment]
@tryptech, I think that the issue from @SanctusStreams is exactly what you are pointing out. Please, check [this](https://github.com/Kalmat/PyWinCtl/issues/11) for more information
