### ISSUE TITLE
Not working after restarting OBS (2560x1440 dual monitors stacked vertically)

### ISSUE THREAD

**Issue by julianmateu** [tryptech/obs-zoom-and-follow#35]
Hi, I have installed the script in Windows 11, OBS 27.2.4 (64 bit), I use 2 monitors in 2560x1440 landscape stacked vertically one on top of the other, with my main monitor being the one on the bottom. I have a scene with Display Capture, and I use that in the script, with zoom configured to the default 1280x720 values. Everything works as expected until I close OBS, and the next time I open it the zoom shortcut produces a strange behaviour, like it zooms to the top left point (infinite zoom?) and the screen capture turns black. Unzooming just leaves the screen at the 1280x720 zoomed in level. So after that initial zoom, the script seems to behave as if the normal level was the zoomed in level (1280x720) and the zoomed level was an infinite zoom on the top left pixel, and there's no way of seeing my entire screen in the 2560x1440 resolution.

My workaround currently is to uninstall the script, and add it back each time I open OBS, which works but is not ideal.

Sorry if this description is not good enough, let me know how I can provide more useful information for debugging the issue.

**Comment by tryptech** [comment]
It's possible that the script isn't getting some information on reload. Given that it goes to the top left, maybe it's not getting screen info (dimensions, position) and/or mouse info. I'll investigate further, but if you discover anything else please let me know.

**Comment by stanixdor** [comment]
Exact same problem here. Hope you can fix it, otherwise the script is super cool.

**Comment by tryptech** [comment]
I think I've fixed this as of https://github.com/tryptech/obs-zoom-and-follow/commit/65d92ff2cf29f6ecc61d49dc58a272c259cf30c7

Could anyone test and confirm that it is fixed on their end?

**Comment by julianmateu** [comment]
Thank you @tryptech , I tested a couple of times and it seems to be working fine after restarting OBS! Awesome job!

**Comment by gabe-over** [comment]
https://drive.google.com/file/d/1jyAq9-3SmDxRVsMse5RL7HQWQbztt8hs/view?usp=drivesdk
