### ISSUE TITLE
Script failed to load Ubuntu 22.04

### ISSUE THREAD

**Issue by AlexTeixeira** [tryptech/obs-zoom-and-follow#36]
## Error using script

Unable to use the script in OBS using Ubuntu OS

###  How it happen

After following the github instruction, I had the script in OBS and this error code appears in a pop-up

###  OS version

![image](https://user-images.githubusercontent.com/6555080/165936925-cd5d63e0-4891-4bc1-a81b-f627e74dab08.png)

###  Error from OBS

`[OBS Mouse Follower.py] Traceback (most recent call last):
[OBS Mouse Follower.py]   File "/run/user/1000/doc/83dd53b/OBS Mouse Follower.py", line 3, in <module>
[OBS Mouse Follower.py]     from ctypes import windll, Structure, c_long, byref
[OBS Mouse Follower.py]   File "/usr/lib/python3.8/ctypes/__init__.py", line 7, in <module>
[OBS Mouse Follower.py]     from _ctypes import Union, Structure, Array
[OBS Mouse Follower.py] ImportError: /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyFloat_Type
[OBS Mouse Follower.py] Traceback (most recent call last):
[OBS Mouse Follower.py]   File "/run/user/1000/doc/83dd53b/OBS Mouse Follower.py", line 3, in <module>
[OBS Mouse Follower.py]     from ctypes import windll, Structure, c_long, byref
[OBS Mouse Follower.py]   File "/usr/lib/python3.8/ctypes/__init__.py", line 7, in <module>
[OBS Mouse Follower.py]     from _ctypes import Union, Structure, Array
[OBS Mouse Follower.py] ImportError: /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyFloat_Type
[OBS Mouse Follower.py] Traceback (most recent call last):
[OBS Mouse Follower.py]   File "/run/user/1000/doc/83dd53b/OBS Mouse Follower.py", line 3, in <module>
[OBS Mouse Follower.py]     from ctypes import windll, Structure, c_long, byref
[OBS Mouse Follower.py]   File "/usr/lib/python3.8/ctypes/__init__.py", line 7, in <module>
[OBS Mouse Follower.py]     from _ctypes import Union, Structure, Array
[OBS Mouse Follower.py] ImportError: /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyFloat_Type
[OBS Mouse Follower.py] Traceback (most recent call last):
[OBS Mouse Follower.py]   File "/run/user/1000/doc/83dd53b/OBS Mouse Follower.py", line 3, in <module>
[OBS Mouse Follower.py]     from ctypes import windll, Structure, c_long, byref
[OBS Mouse Follower.py]   File "/usr/lib/python3.8/ctypes/__init__.py", line 7, in <module>
[OBS Mouse Follower.py]     from _ctypes import Union, Structure, Array
[OBS Mouse Follower.py] ImportError: /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyFloat_Type`

**Comment by tryptech** [comment]
I'm not sure exactly what the issue here is. I think this is the same as https://github.com/tryptech/obs-zoom-and-follow/issues/7#issuecomment-809541256. At that time though, it was an issue with screeninfo-, but not specifically screeninfo-, but rather some other thing entirely with certain Linux distros. Try the most recent commit, PyWinCtl did have some updates to correct somethings in Linux, but I'm not too familiar with the specifics. Let me know if it's still an issue though.
