### ISSUE TITLE
[SOS] Zoom and Follow Script not Loading 

### ISSUE THREAD

**Issue by drewbrockbank** [tryptech/obs-zoom-and-follow#37]
See video for further insight https://www.loom.com/share/d5813979787844188f591274702db7c9.

Zoom and Follow script is not loading. 

I'm on Python 3.6 and I've tried downloading it again. 

Any suggestions?

**Comment by tryptech** [comment]
The only reason I can think of if the script doesn't load is that you need to set the Python36 folder in the Python Settings tab
