### ISSUE TITLE
No mouse follow after zoom.

### ISSUE THREAD

**Issue by gabe-over** [tryptech/obs-zoom-and-follow#38]
I encountered a weird issue: I have one monitor 3440x1440 and the second 2560x1080 above. When I initially installed the script it behave exactly the same as motioned above BUT as soon as I switched the capture source to the second screen, it started zooming as Intended even after switching to the primary screen, although the mouse tracking is not working at all.
Here is a recording of said behavior:
https://drive.google.com/file/d/1jyAq9-3SmDxRVsMse5RL7HQWQbztt8hs/view

**Comment by tryptech** [comment]
Please try again with the current version. I've seen this behavior a few other times, but I want to be sure it's still happening after some recent changes.

**Comment by tryptech** [comment]
Closing from inactivity
