### ISSUE TITLE
Error log.  No zoom or follow.

### ISSUE THREAD

**Issue by NeilWindbourne** [tryptech/obs-zoom-and-follow#41]
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:\Program Files\obs-studio\data\obs-scripting\64bit\OBS PYTHON\zoom_and_follow_mouse.py", line 371, in toggle_zoom
[zoom_and_follow_mouse.py]     zoom.update_source_size()
[zoom_and_follow_mouse.py]   File "C:\Program Files\obs-studio\data\obs-scripting\64bit\OBS PYTHON\zoom_and_follow_mouse.py", line 58, in update_source_size
[zoom_and_follow_mouse.py]     window = pwc.getWindowsWithTitle(data[0])[0]
[zoom_and_follow_mouse.py] IndexError: list index out of range

**Comment by tryptech** [comment]
Can you reproduce with the current version? It would also be good to have the info on if you were zooming in/out, what window you had selected, Python/OBS/OS version.

**Comment by tryptech** [comment]
Closing from inactivity
