### ISSUE TITLE
How to make it work with OBS Flatpak?

### ISSUE THREAD

**Issue by mmBesar** [tryptech/obs-zoom-and-follow#42]
It's working fine with the OBS RPM, but I need to use OBS Flatpak.  
`pywinctl` is installed, but it's not detected by OBS Flatpak!  
```
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "/home/mbesar/Apps/obs/scripts/zoom_and_follow_mouse.py", line 2, in <module>
[zoom_and_follow_mouse.py]     import pywinctl as pwc # version >=0.0.30
[zoom_and_follow_mouse.py] ModuleNotFoundError: No module named 'pywinctl'
```

OS: Fedora 36.  
OBS: 27.2.4 Official Flatpak.

**Comment by tryptech** [comment]
I would double check the version of Python that the Flatpak uses. If possible, I would try to install pywinctl on the Flatpak Python.
