### ISSUE TITLE
Whenever I zoom in all I see is a blurry white square

### ISSUE THREAD

**Issue by CatxOfficial** [tryptech/obs-zoom-and-follow#44]
Ok so, whenever I try to zoom in it looks like a blurry square, and then I checked the source that gets resized with the zoom cropped.
When I click the keybind I have for zoom and follow the resolution changes to 0 on width and 0 on height.
I dunno if it's an error with the version I'm running of pywinctl (0.0.36 - Which dropped the dependecy of numpy) but the only thing that pops up whenever I check the log is:
>[zoom_and_follow_mouse.py] Key 'monitor' does not exist in data

**Comment by tryptech** [comment]
Please try the most recent version of the script, I have updated to try to account this issue with mixed results. I'd like to get more behavior to figure out how best to account for the issue.

**Comment by tryptech** [comment]
For now, I am closing and merging with issue #40.
