### ISSUE TITLE
Doesn't work correctly, zooms to single pixel

### ISSUE THREAD

**Issue by IshanJ25** [tryptech/obs-zoom-and-follow#45]
I have only tested on windows 11:

last commit that works correctly is `68e1aef99cb2d55a60324e1ea9d48f92815f8949`

after that it zooms to a single pixel at top left corner

**Comment by IshanJ25** [comment]
maybe try to restore the previous version with new fixes?

**Comment by JotaRata** [comment]
This is still happening

**Comment by Mamdouh-Abdo** [comment]
me too

**Comment by davidvkimball** [comment]
Same is happening to me. Windows 10.

**Comment by tryptech** [comment]
Please try the most recent commit, there is mixed reports of it working and not exhibiting this behavior.

**Comment by tryptech** [comment]
Duplicate of #40
