### ISSUE TITLE
AttributeError: module 'obspython' has no attribute 'obs_get_frame_interval_ns'

### ISSUE THREAD

**Issue by sdfdger** [tryptech/obs-zoom-and-follow#47]
Python 3.6.8 isn't in PATH, a higher version is.

### Dependencies Installed
Python   3.6.8
pywin32    304
PyWinCtl   0.0.38
win32core  221.36
win32gui   221.6

OBS Python Install Path: `C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64`
OBS 21.1.0 (64bit, windows)

### Script Log
```
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "D:/Folder\zoom_and_follow_mouse.py", line 20, in <module>
[zoom_and_follow_mouse.py]     class CursorWindow:
[zoom_and_follow_mouse.py]   File "D:/Folder\zoom_and_follow_mouse.py", line 39, in CursorWindow
[zoom_and_follow_mouse.py]     refresh_rate = int(obs.obs_get_frame_interval_ns()/1000000)
[zoom_and_follow_mouse.py] AttributeError: module 'obspython' has no attribute 'obs_get_frame_interval_ns'
```

**Comment by tryptech** [comment]
OBS is version 21.
I've coded for version 27 or so, I don't know how far back they added that function to the Python API.
