### ISSUE TITLE
ModuleNotFoundError: No module named 'pywinctl'

### ISSUE THREAD

**Issue by MountainTiger144** [tryptech/obs-zoom-and-follow#48]
I have [Python 3.6.8](https://www.python.org/downloads/release/python-368/) installed and in cmd I installed the PyWinCtl module with:
```
pip install pywinctl==0.0.38
```
However OBS is still spitting out the error:
```
Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:/Program Files/obs-studio/data/obs-plugins/frontend-tools/scripts\zoom_and_follow_mouse.py", line 2, in <module>
[zoom_and_follow_mouse.py]     import pywinctl as pwc # version >=0.0.30
[zoom_and_follow_mouse.py] ModuleNotFoundError: No module named 'pywinctl'
```

I have tried restarting OBS, reinstalling different pywinctl versions >0.0.30, however I still dont see the Python script settings.

**Comment by Mamdouh-Abdo** [comment]
this happend to me make sure u install pywinctl correctly 
this version of script work correctly with me on win 10 64 monitor 24 1080p 
nice hotekey mouse zoom and follow in 1 hotkey

**Comment by uiojaafdosijfafdssf** [comment]
> make sure u install pywinctl correctly

what does that mean?

**Comment by tryptech** [comment]
The issue OBS is throwing is that it's instance of Python is not seeing the PyWinCtl library. Please double check that you do not have multiple versions of Python installed on your computer. In the case that you do, please make sure to install PyWinCtl under Python 3.6.8 and make sure to point OBS to it in the Python Settings tab of the Scripts window.
