### ISSUE TITLE
Zoom Fails to run in a Scene Collection

### ISSUE THREAD

**Issue by TheFlatNoodle** [tryptech/obs-zoom-and-follow#50]
When using the script in the "All Scenes" section of OBS it works as expected and zooms into the two monitors I select in the Zoom Source setting.

I have created a Scene Collection that consists of a single display source (with a unique name across all scenes and collections) when attempting to run the script using the same settings, with the "Zoom Source" set to the display source for the current  Scene Collection the script log pops up with the following error text:

```
[zoom_and_follow_mouse.py] {}
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "D:\XXXX\OBS\Scripts\OBS PYTHON\zoom_and_follow_mouse.py", line 371, in toggle_zoom
[zoom_and_follow_mouse.py]     zoom.update_source_size()
[zoom_and_follow_mouse.py]   File "D:\XXXX\OBS\Scripts\OBS PYTHON\zoom_and_follow_mouse.py", line 66, in update_source_size
[zoom_and_follow_mouse.py]     data = loads(data)['monitor']
[zoom_and_follow_mouse.py] KeyError: 'monitor'
```
The monitor is set up exactly the same as those not in a scene collection and the script has the same settings as well, the only difference is that the display source is now part of a collection.

Can the script not be run within a scene collection or is this something that could perhaps be looked at?

OBS Version: 27.2.4 (Windows 11 64 Bit)
Python Version: 3.6.7 (from Mushiiies Portable Python)
Monitor Resolution: 1920x1080

**Comment by tryptech** [comment]
Scene collections were not yet a feature when I initially wrote the script, but I can take a look to see if it is possible to account for.

Can you give me a screenshot and some steps to replicate your setup as it's a newer feature i'm unfamiliar with?

**Comment by tryptech** [comment]
I'm going to close this for now for no communication. Message back with a screenshot and some steps to replicate your setup if you want me to take a closer look at scene collections again and I'll reopen the issue
