### ISSUE TITLE
Zoom in the upper left corner after pressing hotkey and zooms further in when pressing again

### ISSUE THREAD

**Issue by royselbach** [tryptech/obs-zoom-and-follow#51]
Hello,

I spend a couple of hours on this, but I still have the same problem.
I have 3 connected monitors and the monitor that I would like to have the function work is a 4k (3840 x 2160) monitor.

I tried the hotfix a bit earlier made; but the problem remains the same.

After using the hotkey it zooms in in the top left corner and when I press it again it zooms further into; until I can't see anything. After pressing it again it goes back to the top left corner (not the full screen). Also the mouse follow doesn't work.

OBS 27.2.4 (64 bit)
Python 3.6 (64 bit)
Windows 11 Pro
OS Build 22000.795

**Comment by royselbach** [comment]
Relates to: https://github.com/tryptech/obs-zoom-and-follow/issues/40

**Comment by tryptech** [comment]
Can I get the script log?

**Comment by royselbach** [comment]
13:30:38.294: CPU Name: 12th Gen Intel(R) Core(TM) i9-12900
13:30:38.294: CPU Speed: 2419MHz
13:30:38.294: Physical Cores: 16, Logical Cores: 24
13:30:38.294: Physical Memory: 65151MB Total, 50560MB Free
13:30:38.294: Windows Version: 10.0 Build 22000 (release: 2009; revision: 832; 64-bit)
13:30:38.294: Running as administrator: false
13:30:38.294: Aero is Enabled (Aero is always on for windows 8 and above)
13:30:38.294: Windows 10 Gaming Features:
13:30:38.294: 	Game DVR: On
13:30:38.295: Sec. Software Status:
13:30:38.296: 	AVG Antivirus: enabled (AV)
13:30:38.296: 	Microsoft Defender Antivirus: disabled (AV)
13:30:38.296: 	Microsoft Firewall: enabled (FW)
13:30:38.297: Current Date/Time: 2022-08-02, 13:30:38
13:30:38.297: Browser Hardware Acceleration: true
13:30:38.297: Hide OBS windows from screen capture: false
13:30:38.297: Qt Version: 5.15.2 (runtime), 5.15.2 (compiled)
13:30:38.297: Portable mode: false
13:30:38.561: OBS 27.2.4 (64-bit, windows)
13:30:38.561: ---------------------------------
13:30:38.598: ---------------------------------
13:30:38.599: audio settings reset:
13:30:38.599: 	samples per sec: 48000
13:30:38.599: 	speakers:        2
13:30:38.603: ---------------------------------
13:30:38.603: Initializing D3D11...
13:30:38.603: Available Video Adapters: 
13:30:38.605: 	Adapter 0: NVIDIA GeForce RTX 3060 Ti
13:30:38.605: 	  Dedicated VRAM: 4146069504
13:30:38.605: 	  Shared VRAM:    4093599744
13:30:38.605: 	  PCI ID:         10de:2489
13:30:38.605: 	  Driver Version: 30.0.15.1295
13:30:38.605: 	  output 0:
13:30:38.605: 	    name=DELL U2720Q
13:30:38.605: 	    pos={0, 0}
13:30:38.605: 	    size={3840, 2160}
13:30:38.605: 	    attached=true
13:30:38.605: 	    refresh=60
13:30:38.605: 	    space=RGB_FULL_G22_NONE_P709
13:30:38.605: 	    sdr_white_nits=80
13:30:38.605: 	    nit_range=[min=0.500000, max=270.000000, max_full_frame=270.000000]
13:30:38.605: 	  output 1:
13:30:38.605: 	    name=DELL U2414H
13:30:38.605: 	    pos={3840, 0}
13:30:38.605: 	    size={1080, 1920}
13:30:38.605: 	    attached=true
13:30:38.605: 	    refresh=60
13:30:38.605: 	    space=RGB_FULL_G22_NONE_P709
13:30:38.605: 	    sdr_white_nits=80
13:30:38.605: 	    nit_range=[min=0.500000, max=270.000000, max_full_frame=270.000000]
13:30:38.605: 	  output 2:
13:30:38.605: 	    name=DELL U2414H
13:30:38.605: 	    pos={-1920, 522}
13:30:38.605: 	    size={1920, 1080}
13:30:38.605: 	    attached=true
13:30:38.605: 	    refresh=60
13:30:38.605: 	    space=RGB_FULL_G22_NONE_P709
13:30:38.605: 	    sdr_white_nits=80
13:30:38.605: 	    nit_range=[min=0.500000, max=270.000000, max_full_frame=270.000000]
13:30:38.605: 	Adapter 1: Intel(R) UHD Graphics 770
13:30:38.605: 	  Dedicated VRAM: 134217728
13:30:38.605: 	  Shared VRAM:    4093599744
13:30:38.605: 	  PCI ID:         8086:4680
13:30:38.605: 	  Driver Version: 30.0.101.1660
13:30:38.607: Loading up D3D11 on adapter NVIDIA GeForce RTX 3060 Ti (0)
13:30:38.649: D3D11 loaded successfully, feature level used: b000
13:30:38.649: DXGI increase maximum frame latency success
13:30:38.649: D3D11 GPU priority setup failed (not admin?)
13:30:38.888: ---------------------------------
13:30:38.888: video settings reset:
13:30:38.888: 	base resolution:   3840x2160
13:30:38.888: 	output resolution: 3840x2160
13:30:38.888: 	downscale filter:  Lanczos
13:30:38.888: 	fps:               60/1
13:30:38.888: 	format:            NV12
13:30:38.888: 	YUV mode:          709/Full
13:30:38.888: NV12 texture support enabled
13:30:38.889: Audio monitoring device:
13:30:38.889: 	name: Default
13:30:38.889: 	id: default
13:30:38.889: ---------------------------------
13:30:38.902: No AJA devices found, skipping loading AJA UI plugin
13:30:38.902: Failed to initialize module 'aja-output-ui.dll'
13:30:38.911: No AJA devices found, skipping loading AJA plugin
13:30:38.911: Failed to initialize module 'aja.dll'
13:30:38.911: Skipping module '../../obs-plugins/64bit/chrome_elf.dll', not an OBS plugin
13:30:38.915: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
13:30:38.918: Failed to load 'en-US' text for module: 'decklink-captions.dll'
13:30:38.923: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
13:30:38.950: [AMF] Unable to load 'amfrt64.dll', error code 126.
13:30:38.951: [AMF] AMF Test failed due to one or more errors.
13:30:38.951: Failed to initialize module 'enc-amf.dll'
13:30:39.025: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin
13:30:39.025: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin
13:30:39.025: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin
13:30:39.055: [obs-browser]: Version 2.17.13
13:30:39.055: [obs-browser]: CEF Version 95.0.0-MediaHandler.2467+g8092a57+chromium-95.0.4638.69
13:30:39.073: NVENC supported
13:30:39.078: [noise suppress]: NVIDIA RTX denoiser disabled, redistributable not found
13:30:39.136: Failed to load 'en-US' text for module: 'StreamDeckPlugin.dll'
13:30:39.136: <StreamDeck> [Server] Listening on '127.0.0.1:28186'.
13:30:39.147: Failed to load 'en-US' text for module: 'StreamDeckPlugin1.dll'
13:30:39.158: [vlc-video]: VLC 3.0.17.4 Vetinari found, VLC video source enabled
13:30:39.167: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
13:30:39.167: No blackmagic support
13:30:39.363: ---------------------------------
13:30:39.363:   Loaded Modules:
13:30:39.363:     win-wasapi.dll
13:30:39.363:     win-mf.dll
13:30:39.363:     win-dshow.dll
13:30:39.363:     win-decklink.dll
13:30:39.363:     win-capture.dll
13:30:39.363:     vlc-video.dll
13:30:39.363:     text-freetype2.dll
13:30:39.363:     StreamDeckPlugin1.dll
13:30:39.363:     StreamDeckPlugin.dll
13:30:39.363:     rtmp-services.dll
13:30:39.363:     obs-x264.dll
13:30:39.363:     obs-vst.dll
13:30:39.363:     obs-transitions.dll
13:30:39.363:     obs-text.dll
13:30:39.363:     obs-qsv11.dll
13:30:39.363:     obs-outputs.dll
13:30:39.363:     obs-filters.dll
13:30:39.363:     obs-ffmpeg.dll
13:30:39.363:     obs-browser.dll
13:30:39.363:     image-source.dll
13:30:39.363:     frontend-tools.dll
13:30:39.363:     decklink-ouput-ui.dll
13:30:39.363:     decklink-captions.dll
13:30:39.363:     coreaudio-encoder.dll
13:30:39.363: ---------------------------------
13:30:39.363: ==== Startup complete ===============================================
13:30:39.400: All scene data cleared
13:30:39.400: ------------------------------------------------
13:30:39.507: [Python: zoom_and_follow_mouse.py] Source update
13:30:39.510: [Python: zoom_and_follow_mouse.py] No sources, likely OBS startup.
13:30:39.510: [Python: zoom_and_follow_mouse.py] Source Name: Display Capture
13:30:39.510: [win-wasapi: 'Desktop Audio'] update settings:
13:30:39.510: 	device id: default
13:30:39.510: 	use device timing: 1
13:30:39.512: [Loaded global audio device]: 'Desktop Audio'
13:30:39.512: [win-wasapi: 'Mic/Aux'] update settings:
13:30:39.512: 	device id: {0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}
13:30:39.512: 	use device timing: 0
13:30:39.513: [noise suppress: 'Noise Suppression'] NVAFX redist is not installed.
13:30:39.513: [WASAPISource::TryInitialize]:[{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}] Failed to enumerate device: 80070490
13:30:39.513: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:30:39.513: User selected new VST plugin: 'C:/Program Files/VSTPlugins/ReaPlugs/reaeq-standalone.dll'
13:30:39.522: [Loaded global audio device]: 'Mic/Aux'
13:30:39.522:     - filter: 'Noise Suppression' (noise_suppress_filter_v2)
13:30:39.522:     - filter: 'Compressor' (compressor_filter)
13:30:39.522:     - filter: 'VST 2.x Plug-in' (vst_filter)
13:30:39.522:     - filter: 'Noise Gate' (noise_gate_filter)
13:30:39.522:     - filter: 'Limiter' (limiter_filter)
13:30:39.522:     - filter: 'Invert Polarity' (invert_polarity_filter)
13:30:39.525: [win-wasapi: 'Mic/Aux - Yeti'] update settings:
13:30:39.525: 	device id: {0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}
13:30:39.525: 	use device timing: 0
13:30:39.525: [WASAPISource::TryInitialize]:[{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}] Failed to enumerate device: 80070490
13:30:39.525: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:30:39.535: WASAPI: Device 'Headphones (C-Media USB2.0 Audio)' [48000 Hz] initialized
13:30:39.547: [Media Source 'Circle Swipe (Stinger)']: settings:
13:30:39.547: 	input:                   C:/Users/User/Documents/OBS/10 Matte Transitions - Free/Transitions/07/SFX/Blue.webm
13:30:39.547: 	input_format:            (null)
13:30:39.547: 	speed:                   100
13:30:39.547: 	is_looping:              no
13:30:39.547: 	is_linear_alpha:         no
13:30:39.547: 	is_hw_decoding:          yes
13:30:39.547: 	is_clear_on_media_end:   yes
13:30:39.547: 	restart_on_activate:     yes
13:30:39.547: 	close_when_inactive:     no
13:30:39.547: Switched to scene 'Canon - Full'
13:30:39.547: ------------------------------------------------
13:30:39.547: Loaded scenes:
13:30:39.547: - scene 'Canon - Full':
13:30:39.547:     - source: 'Video/Canon' (dshow_input)
13:30:39.547:     - source: 'Mic/Aux - Yeti' (wasapi_input_capture)
13:30:39.547: - scene 'Canon + Mid Screen':
13:30:39.547:     - source: 'Mic/Aux - Yeti' (wasapi_input_capture)
13:30:39.547:     - source: 'Webcam - Canon' (group)
13:30:39.547:         - source: 'Video/Canon' (dshow_input)
13:30:39.547: - scene 'Logitech - Full':
13:30:39.547:     - source: 'Mic/Aux - Yeti' (wasapi_input_capture)
13:30:39.548:     - source: 'Video/Logitech' (dshow_input)
13:30:39.548: - scene 'Logitech + Mid Screen':
13:30:39.548:     - source: 'Mic/Aux - Yeti' (wasapi_input_capture)
13:30:39.548:     - source: 'Webcam - Logi' (group)
13:30:39.548:         - source: 'Video/Logitech' (dshow_input)
13:30:39.548: - scene 'Canon - Full 2':
13:30:39.548:     - source: 'Video/Canon' (dshow_input)
13:30:39.548:     - source: 'Mic/Aux - Yeti' (wasapi_input_capture)
13:30:39.548: ------------------------------------------------
13:30:39.560: [Media Source 'Red Arrow (Stinger)']: settings:
13:30:39.560: 	input:                   C:/Users/User/Documents/OBS/Free Animated Stream Package/Transition/MOVs/Transition Red.mov
13:30:39.560: 	input_format:            (null)
13:30:39.560: 	speed:                   100
13:30:39.560: 	is_looping:              no
13:30:39.560: 	is_linear_alpha:         no
13:30:39.560: 	is_hw_decoding:          yes
13:30:39.560: 	is_clear_on_media_end:   yes
13:30:39.560: 	restart_on_activate:     yes
13:30:39.560: 	close_when_inactive:     no
13:30:39.560: [Media Source 'Skewed Strips (Stinger)']: settings:
13:30:39.560: 	input:                   C:/Users/User/Documents/OBS/Skewed Strips Wipe/WEBM/Without Sound/Skewed Strips (Blue).webm
13:30:39.560: 	input_format:            (null)
13:30:39.560: 	speed:                   100
13:30:39.560: 	is_looping:              no
13:30:39.560: 	is_linear_alpha:         no
13:30:39.560: 	is_hw_decoding:          yes
13:30:39.560: 	is_clear_on_media_end:   yes
13:30:39.560: 	restart_on_activate:     yes
13:30:39.560: 	close_when_inactive:     no
13:30:39.560: warning: Could not update timestamps for skipped samples.
13:30:39.676: ---------------------------------
13:30:39.676: [DShow Device: 'Video/Canon'] settings updated: 
13:30:39.676: 	video device: EOS Webcam Utility
13:30:39.676: 	video path: \\?\root#eoswebcamsource#0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\eoswebcamcamerasource
13:30:39.676: 	resolution: 1024x576
13:30:39.676: 	flip: 0
13:30:39.676: 	fps: 30.00 (interval: 333333)
13:30:39.676: 	format: XRGB
13:30:39.676: 	buffering: disabled
13:30:39.677: DShow: HDevice::ConnectPins: failed to connect pins (0x8004022A): 
13:30:39.753: ---------------------------------
13:30:39.753: [DShow Device: 'Video/Logitech'] settings updated: 
13:30:39.753: 	video device: HD Pro Webcam C920
13:30:39.753: 	video path: \\?\usb#vid_046d&pid_0892&mi_00#7&ea751c6&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global
13:30:39.753: 	resolution: 640x480
13:30:39.753: 	flip: 0
13:30:39.753: 	fps: 30.00 (interval: 333333)
13:30:39.753: 	format: YUY2
13:30:39.753: 	buffering: disabled
13:30:42.512: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:30:42.525: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:30:45.513: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:30:45.526: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:30:48.514: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:30:48.527: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:30:51.514: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:30:51.527: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:30:54.515: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:30:54.528: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:30:57.516: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:30:57.529: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:31:00.516: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:31:00.529: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:31:03.517: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:31:03.529: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:31:06.518: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:31:06.530: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:31:09.519: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:31:09.531: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:31:12.519: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:31:12.531: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:31:15.520: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:31:15.532: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:31:18.520: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:31:18.532: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:31:21.520: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:31:21.533: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:31:24.520: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:31:24.534: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:31:27.521: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:32:13.360: Last log entry repeated for 31 more lines
13:32:13.360: User switched to scene 'Logitech - Full'
13:32:14.077: A sprite cannot be drawn without a width/height
13:32:15.528: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:32:15.542: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:32:18.529: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:32:18.542: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:32:21.530: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:32:21.542: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:32:24.530: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:32:24.543: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:32:27.530: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:32:27.543: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:32:30.530: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:32:30.544: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:32:33.531: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:32:33.544: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:32:33.626: [duplicator-monitor-capture: 'Display Capture'] update settings:
13:32:33.626: 	display: 1 (3840x2160)
13:32:33.626: 	cursor: true
13:32:33.626: 	method: DXGI
13:32:33.629: User added source 'Display Capture' (monitor_capture) to scene 'Logitech - Full'
13:32:36.531: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:32:36.545: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:32:39.346: [Python: zoom_and_follow_mouse.py] Updating Source List
13:32:39.349: [Python: zoom_and_follow_mouse.py] New source: True
13:32:39.350: [Python: zoom_and_follow_mouse.py] Updating Monitor List
13:32:39.352: [Python: zoom_and_follow_mouse.py] Monitor override list updated
13:32:39.532: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:32:39.546: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:32:42.533: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:32:42.546: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:32:43.774: [Python: zoom_and_follow_mouse.py] Source update
13:32:43.776: [Python: zoom_and_follow_mouse.py] Source Name: Display Capture
13:32:43.864: [Python: zoom_and_follow_mouse.py] Source update
13:32:43.866: [Python: zoom_and_follow_mouse.py] Source Name: Display Capture
13:32:45.533: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:32:45.547: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:32:48.533: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:32:48.547: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:32:51.534: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:32:51.548: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:32:54.535: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:32:54.548: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:32:54.864: [Python: zoom_and_follow_mouse.py] Source Type: monitor_capture
13:32:54.864: [Python: zoom_and_follow_mouse.py] Key 'monitor' does not exist in {}
13:32:54.864: [Python: zoom_and_follow_mouse.py] Zoom: True
13:32:54.864: [Python: zoom_and_follow_mouse.py] Mouse position: [332, 1029]
13:32:56.546: [Python: zoom_and_follow_mouse.py] Zoom: False
13:32:57.536: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:32:57.549: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:32:57.643: [Python: zoom_and_follow_mouse.py] Source Type: monitor_capture
13:32:57.643: [Python: zoom_and_follow_mouse.py] Key 'monitor' does not exist in {}
13:32:57.643: [Python: zoom_and_follow_mouse.py] Zoom: True
13:32:57.643: [Python: zoom_and_follow_mouse.py] Mouse position: [347, 995]
13:32:58.460: [Python: zoom_and_follow_mouse.py] Zoom: False
13:32:59.378: [Python: zoom_and_follow_mouse.py] Source Type: monitor_capture
13:32:59.378: [Python: zoom_and_follow_mouse.py] Key 'monitor' does not exist in {}
13:32:59.378: [Python: zoom_and_follow_mouse.py] Zoom: True
13:32:59.378: [Python: zoom_and_follow_mouse.py] Mouse position: [347, 995]
13:33:00.537: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:33:00.549: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:33:01.364: [Python: zoom_and_follow_mouse.py] Zoom: False
13:33:01.825: [Python: zoom_and_follow_mouse.py] Source Type: monitor_capture
13:33:01.825: [Python: zoom_and_follow_mouse.py] Key 'monitor' does not exist in {}
13:33:01.825: [Python: zoom_and_follow_mouse.py] Zoom: True
13:33:01.825: [Python: zoom_and_follow_mouse.py] Mouse position: [-1247, 953]
13:33:03.537: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:33:03.549: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:33:06.538: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:33:06.549: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:33:09.538: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:33:09.549: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:33:12.539: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:33:12.550: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:33:15.540: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:33:15.551: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start
13:33:18.540: WASAPI: Device '{0.0.1.00000000}.{58630aa0-704d-4b06-8f03-e1c442256566}' failed to start
13:33:18.551: WASAPI: Device '{0.0.1.00000000}.{8198cac0-cbab-4550-86d3-606c106088cb}' failed to start

**Comment by tryptech** [comment]
Use the monitor override. I won't be digging through the entire OBS log as it's not particularly relevant. If OBS isn't reporting the monitor ID via its Python API, manually select it with the override

**Comment by royselbach** [comment]
Oh that easy! Works <3
