### ISSUE TITLE
Can this package work with latest 3.10.6 python?

### ISSUE THREAD

**Issue by matthewharwood** [tryptech/obs-zoom-and-follow#57]
I'm struggling to get this to work. The 3.6.x python is at end of life and not downloadable from python as an exe... 
Is this pilot error or is 3.10.6 really incompatitable with 3.6.x.. This script seems to great but yeah not showing props on obs

<img width="598" alt="image" src="https://user-images.githubusercontent.com/1505266/183301390-b1000cd8-c76a-475a-8dfb-7ff4e0309489.png">

**Comment by matthewharwood** [comment]
Closing issue.  investigated more... it's OBS not this package. We do need to use 3.6.x

**Comment by tryptech** [comment]
As a note, you should be able to use any python 3 version as of OBS 28+.
