### ISSUE TITLE
Mouse movement being picked from incorrect monitor

### ISSUE THREAD

**Issue by HQRaja** [tryptech/obs-zoom-and-follow#58]
After I had reported #54 and you provided the update, I verified that everything was working as expected, and then didn't really get a chance to use it. Today when attempting to use the feature, I ran into some very strange behavior.

Zoom works perfectly fine with the custom monitor dimensions I provided but when it comes to follow, nothing happens while I'm moving the mouse on the screen being shared, which is my external monitor. However, I discovered this by accident as I moved my mouse cursor to the primary monitor: moving the mouse there within the dimensions specified in the plugin's settings as custom resolution does trigger the follow.

I have tried unloading the script, deleting the monitor source altogether, creating the source again, loading and configuring the script again, but to no avail. And what's most strange about this is I hadn't changed anything in the screen scene, the display capture source, or the script's settings in OBS since last verifying that it worked. The only changes I had made were in other scenes.

To reiterate briefly: The display source being captured is display B, and the script is set to use display B as well, but follow happens when I move my mouse on display A, and not when I move the mouse on display B.

I'm stumped at what might be causing such behavior.

**Comment by tryptech** [comment]
Yeah, I've had this happen on my own setup as well. Sometimes OBS's monitor ID and the OS's monitor ID get out of sync. There is a toggle for manual monitor override to manually select the monitor to use for tracking if this is ever the case. Please try it out and let me know how it goes.

**Comment by HQRaja** [comment]
Yes, I've been using manual monitor override throughout (both before and after the issue started happening.)

**Comment by tryptech** [comment]
I believe this should be addressed in the most recent commit. Please test it and see if that is the case on your system. If the problem persists, please let me know and I will reopen the issue.

**Comment by HQRaja** [comment]
Seems to have been fixed in the update you mentioned. (I was travelling and just got to try it.)

Thank you!
