### ISSUE TITLE
Not working with OBS 28 (64-bit) on Windows 11 with Python 3.10

### ISSUE THREAD

**Issue by kumueric** [tryptech/obs-zoom-and-follow#61]
(Thank you VERY much -- I have been using zoom-and-follow reliably for several years--through many upgrades of OBS--but it is not working for me now....)
System: Windows 11 64-bit kept up-to-date with Windows Updates
OBS Studio:  28.0.0 (64 bit)
Python:  3.10.6 (64-bit)
[... ran installer with pip installed to: C:\Program Files\obs-studio\py\python310]
PyWinCtl: 0.0.38
[... executed the following in Python directory (with Admin privs)> `.\python.exe -m pip install pywinctl`]
Configured OBS Studio: Tools --> Scripts
Python Install Path:  C:\Program Files\obs-studio\py\python310
Script:  C:\Program Files\obs-studio\py\src\zoom_and_follow_mouse.py

When I launch OBS Studio, the Script Log opens with these messages:
[zoom_and_follow_mouse.py] 
C:\Program Files/obs-studio/py/src\zoom_and_follow_mouse.py:566: SyntaxWarning: "is" with a literal. Did you mean "=="?
`     if source_string is "":`

Non-initial update
Source 'Display Capture' not found.
None
Source Name: 

_NOTE: My Source is: "Display Capture"_

When I open Settings --> Hotkeys, I enter my usual keys, and they do NOT work for me:  No zoom.

Here is a part of my Script Log:
[zoom_and_follow_mouse.py] Zoom: True
[zoom_and_follow_mouse.py] Mouse position: [-1573, 236]
[zoom_and_follow_mouse.py] Zoom: True
[zoom_and_follow_mouse.py] Mouse position: [-1589, 351]
[zoom_and_follow_mouse.py] Zoom: True
[zoom_and_follow_mouse.py] Mouse position: [-1589, 351]
[zoom_and_follow_mouse.py] Tracking: True
[zoom_and_follow_mouse.py] Tracking: False

_It seems to me that the Zoom Hotkey is being received by the script, but it is not "toggling" from True to False (and it is NOT having the zoom effect either).  However, the mouse tracking seems to be toggling from on to off._

Again: Thank you VERY much.

PS:  At the very top of the script, please consider adding a DOCSTRING like:
`"""\  `
` 
This script is written to be called from OBS Studio.  It allows users to zoom and follow the mouse.  For more information, please visit the project:
https://github.com/tryptech/obs-zoom-and-follow`
`"""`

**Comment by tryptech** [comment]
Should be fixed now. I think I actually solved this issue a while back but forgot to change the initial state of one variable. Please give it a try and let me know how it goes.

**Comment by kumueric** [comment]
Thank you VERY MUCH for the quick response....   Unfortunately, when I zoom-in, what happens is the visible portion shrinks to the upper left but the magnification is still static at 100%, so OBS captures a clipped rectangle with a black vertical strip across the far right and a black horizontal strip across the bottom (a flipped "L").  [When I move the mouse around within the zoomed-in view, the motion is perfect (the frame is set, but when I move the mouse towards an edge, the frame shifts; then when I move the mouse back towards center, the frame is set)].  So, the issue that I have now is that the magnification remains 100%.  Instead of the magnification remaining 100% and the border shrinking-in to the upper left, what should happen is that the magnification should increase to scale so that the image fills the screen and covers over the black strips on the right and bottom.  Thank you VERY much.

**Comment by tryptech** [comment]
I think for that case, the source should be given a bounding box, and set to "scale to inner bounds". I haven't found a way to set that via the addon, so it has to be set manually in that case.

**Comment by kumueric** [comment]
Yes, that was it!  Thank you VERY much!   In case it helps, here are the steps:

Source set to: Display Capture
Right-click "Display Capture"
Select: Transform
Select: Edit Transform
In "Bounding Box Type," select: Scale to inner bounds.

If you're in the US, have a GREAT long Labor Day Weekend!
🥇
