### ISSUE TITLE
Issue with KeyError: 'source'

### ISSUE THREAD

**Issue by AlexBsalas** [tryptech/obs-zoom-and-follow#65]
Hello To the Forum,

I am new and not very good in IT or programming things.

But I have an issue with the script of the mouse zoom and following.

I have installed python. It is on version 3.6.8
For that I did first: python -m pip install pynput
Worked well no errors.
Then I did: python -m pip install screeninfo
Worked well too. No errors.

I downloaded the zip file from github and extracted it to my C: folder.
I opened OBS went to scripts. I added "mouse zoom and follow".
When I do that I get a message:

[zoom_and_follow_mouse.py] Source update
[zoom_and_follow_mouse.py] Source Name: Bildschirmaufnahme
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py] File "C:/Program Files/obs-zoom-and-follow-master\zoom_and_follow_mouse.py", line 797, in script_save
[zoom_and_follow_mouse.py] hotkey_save_array = obs.obs_hotkey_save(zoom_id_tog)
[zoom_and_follow_mouse.py] TypeError: in method 'obs_hotkey_save', argument 1 of type 'obs_hotkey_id'
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py] File "C:/Program Files/obs-zoom-and-follow-master\zoom_and_follow_mouse.py", line 770, in script_load
[zoom_and_follow_mouse.py] [source, source_type] = load_settings['source'].split("||")
[zoom_and_follow_mouse.py] KeyError: 'source'
[zoom_and_fo
![OBS_crash_message](https://user-images.githubusercontent.com/114077761/191503076-9c5ab10c-cac3-45fb-b6e4-af694f646ac3.png)
llow_mouse.py] Updating Source List
[zoom_and_follow_mouse.py] New source: True
[zoom_and_follow_mouse.py] Updating Monitor List
[zoom_and_follow_mouse.py] Monitor override list updated
[zoom_and_follow_mouse.py] Updating Source List
[zoom_and_follow_mouse.py] New source: True
[zoom_and_follow_mouse.py] Updating Monitor List
[zoom_and_follow_mouse.py] Monitor override list updated
To me it looks good so far.

But when I go to the settings and Hotkeys, I cannot find anything related to the script.
But instead I get an error message and now I don't know what to do:

[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py] File "C:/Program Files/obs-zoom-and-follow-master\zoom_and_follow_mouse.py", line 797, in script_save
[zoom_and_follow_mouse.py] hotkey_save_array = obs.obs_hotkey_save(zoom_id_tog)
[zoom_and_follow_mouse.py] TypeError: in method 'obs_hotkey_save', argument 1 of type 'obs_hotkey_id'

If it helps, I work with OBS 27.2.4 (64-bit, windows)

When I close OBS it crashes and gives the error message enclosed in the png.

When I reopen OBS, I get this message:
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:/Program Files/obs-zoom-and-follow-master\zoom_and_follow_mouse.py", line 770, in script_load
[zoom_and_follow_mouse.py]     [source, source_type] = load_settings['source'].split("||")
[zoom_and_follow_mouse.py] KeyError: 'source'

Does anyone knows what I can do to fix this?

Thank you so much for your help.

**Comment by tryptech** [comment]
Hmm... for now I'm updating the script to catch whenever that error comes up instead of failing outright. Can you update to the most recent version ( should say v.2022.09.21 in the script settings ) and let me know if the issue persists?
