### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by pedrinj66** [tryptech/obs-zoom-and-follow#66]
hi, i just install zoom and follow and showed me this error

[zoom_and_follow_mouse.py] {}
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:\Users\pedrinj66\OneDrive\Desktop\stream downloads\OBS PYTHON\zoom_and_follow_mouse.py", line 371, in toggle_zoom
[zoom_and_follow_mouse.py]     zoom.update_source_size()
[zoom_and_follow_mouse.py]   File "C:\Users\pedrinj66\OneDrive\Desktop\stream downloads\OBS PYTHON\zoom_and_follow_mouse.py", line 66, in update_source_size
[zoom_and_follow_mouse.py]     data = loads(data)['monitor']
[zoom_and_follow_mouse.py] KeyError: 'monitor'

**Comment by tryptech** [comment]
I'm looking through the code, but line 371 is not zoom.update_source_size() and line 66 is not data = loads(data)['monitor']

I strongly suggest you update your version of the script to the most recent version. If your script settings do not say "v.2022.09.21", you are on an older version that I am no longer supporting

**Comment by tryptech** [comment]
Closing because stale
