### ISSUE TITLE
What is Zoom Source 

### ISSUE THREAD

**Issue by AmrShalaby** [tryptech/obs-zoom-and-follow#69]
Its appear to be blank 
i cant Choose any source 
I use last obs update

**Comment by tryptech** [comment]
1. What version of the script are you on? I don't experience this behavior with script version 2022.09.22 and with display capture sources.
2. What OS version are you using? I have the easiest time troubleshooting Windows, and have a difficult time troubleshooting MacOS.
3. What Python version are you using? If you're one OBS 28 you should be able to use any version of Python but maybe it doesn't work with certain versions.
4. Please share the script log so I can see what's going on.

For further reference in any repository, please create an issue with information. The three lines you've sent give me nothing to go off of and no way to debug.

**Comment by tryptech** [comment]
Closing because stale
