### ISSUE TITLE
ModuleNotFoundError: No module named 'win32api'

### ISSUE THREAD

**Issue by Leondrix** [tryptech/obs-zoom-and-follow#71]
OBS version 28.0.2

[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:/Program Files/obs-studio/data/obs-plugins/frontend-tools/scripts\zoom_and_follow_mouse.py", line 9, in <module>
[zoom_and_follow_mouse.py]     import pywinctl as pwc # version >=0.0.38
[zoom_and_follow_mouse.py]   File "C:\Users\hp\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinctl\__init__.py", line 673, in <module>
[zoom_and_follow_mouse.py]     from ._pywinctl_win import (
[zoom_and_follow_mouse.py]   File "C:\Users\hp\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinctl\_pywinctl_win.py", line 13, in <module>
[zoom_and_follow_mouse.py]     import win32api
[zoom_and_follow_mouse.py] ModuleNotFoundError: No module named 'win32api'

I already tried ***pip install pypiwin32*** and ***python Scripts/pywin32_postinstall.py -install***

![image_2022-09-26_161114517](https://user-images.githubusercontent.com/81205668/192226260-86e94f55-54bb-4c3f-b6d5-14ba8974136d.png)

**Comment by super-ibby** [comment]
Not the repo owner / contributor, but looks like a `pywinctl` issue.

What is the version of `pywinctl` installed, i.e. the output of the following in Command Prompt:

```
python
import pywinctl
pywinctl.__version__
quit()
```

The instructions on the [`pywinctl` repo](https://github.com/Kalmat/PyWinCtl/) state that you can use the `--force-reinstall` flag to ensure dependencies are updated:

<img width="873" alt="Screenshot 2022-09-26 at 8 14 26 AM" src="https://user-images.githubusercontent.com/112219012/192274884-5db79c28-610b-416b-8260-076f59900c65.png">

**Comment by Leondrix** [comment]
> Not the repo owner / contributor, but looks like a `pywinctl` issue.
> 
> What is the version of `pywinctl` installed, i.e. the output of the following in Command Prompt:
> 
> ```
> python
> import pywinctl
> pywinctl.__version__
> quit()
> ```
> 
> The instructions on the [`pywinctl` repo](https://github.com/Kalmat/PyWinCtl/) state that you can use the `--force-reinstall` flag to ensure dependencies are updated:
> 
> <img alt="Screenshot 2022-09-26 at 8 14 26 AM" width="873" src="https://user-images.githubusercontent.com/112219012/192274884-5db79c28-610b-416b-8260-076f59900c65.png">

Thank you! It's fixed now. I did see the instructions before but first I didn't direct my cmd path to my download folder since the ***PyWinCtl-0.0.39-py3-none-any.whl*** was there and didn't use ***--force-reinstall***

![image_2022-09-27_001914798](https://user-images.githubusercontent.com/81205668/192328826-a14fb613-40ad-4354-9a12-8814d8a11237.png)
