### ISSUE TITLE
ModuleNotFoundError: No module named 'pywinctl'

### ISSUE THREAD

**Issue by FilipChalupa** [tryptech/obs-zoom-and-follow#73]
```
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:\Program Files/obs-studio/data/obs-plugins/frontend-tools/scripts\zoom_and_follow_mouse.py", line 21, in <module>
[zoom_and_follow_mouse.py]     import pywinctl as pwc # version >=0.0.38
[zoom_and_follow_mouse.py] ModuleNotFoundError: No module named 'pywinctl'
```

![image](https://user-images.githubusercontent.com/1045362/194645674-696e92ce-e245-40b4-be43-c4abf99d36cb.png)

**Comment by Vashinator** [comment]
@FilipChalupa to me that looks like pywinctl isn't installed.

Did you run:

**Comment by tryptech** [comment]
Agreed, this looks like an issue of not installing pywinctl to the version of python that OBS is pointing to

**Comment by tryptech** [comment]
Closing as python installation issues are not in scope of support.
