### ISSUE TITLE
Empty zoom source list [Linux] [BSPWM]

### ISSUE THREAD

**Issue by Flinner** [tryptech/obs-zoom-and-follow#76]
This is related to #74 but i see no error logs at all.

testing these lines manually

https://github.com/tryptech/obs-zoom-and-follow/blob/1006b7b33ea69b3cde75a9a8ce0ec17a0622a5c1/zoom_and_follow_mouse.py#L60-L67

gives

```py
>>> import pywinctl as pwc
>>> pwc.getAllWindows()
[LinuxWindow(hWnd=<class 'Xlib.display.Window'>(0x01200003)), .....]
>>> pwc.getAllScreens()
{'eDP-1': ........}}

```

so the library works (?) for me, but the source list is still empty

I use v2022.09.26, copied the script directly from the repo (so it is latest version) 

when i press "Refresh  list of sources" nothing happens, zero logs from the script

thanks for making this tool, any help is appreciated

**Comment by tryptech** [comment]
Thank you for finding that information, I have updated the script accordingly, but I'm not sure if monitor sizes will be reported properly. If not, you will have to continue to manually set the screen size.
