### ISSUE TITLE
After closing OBS I receive A Crash Notice

### ISSUE THREAD

**Issue by LEOsMIND** [tryptech/obs-zoom-and-follow#77]
Since I installed the script, my OBS crashes when I close OBS.
When I don't use the Skript or disable it, the crashes don't happen. 
I attached the Crashing Log
[Crash 2022-10-18 12-54-04.txt](https://github.com/tryptech/obs-zoom-and-follow/files/9810069/Crash.2022-10-18.12-54-04.txt)
Any Ideas. I love the Skript and would hate to disable it.

**Comment by santiyounger** [comment]
I had the same issue, not sure how to solve this. Hopefully this can be solves soon, I really like this script too

**Comment by tryptech** [comment]
If this is still an issue, please reproduce and resubmit with current working versions of python, OBS, script and dependencies.
