### ISSUE TITLE
Error when press hot key

### ISSUE THREAD

**Issue by orsgah** [tryptech/obs-zoom-and-follow#79]
[zoom_and_follow_mouse.py] {'capture_cursor': True}
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:\Program Files\obs-studio\OBS PYTHON\zoom_and_follow_mouse.py", line 371, in toggle_zoom
[zoom_and_follow_mouse.py]     zoom.update_source_size()
[zoom_and_follow_mouse.py]   File "C:\Program Files\obs-studio\OBS PYTHON\zoom_and_follow_mouse.py", line 66, in update_source_size
[zoom_and_follow_mouse.py]     data = loads(data)['monitor']
[zoom_and_follow_mouse.py] KeyError: 'monitor'

**Comment by ch1ntoo** [comment]
Same problem. Plz help

**Comment by tarazhong** [comment]
change line 227 to monitor_id = data.get('monitor_id', None)

**Comment by praisetracks** [comment]
Hello,
I just installed Python and the script. I am getting a similar error to the above when triggering the hotkey. I found the line and changed the code as recommended but this error was generated afterward.

[zoom_and_follow_mouse.py] {'method': 2, 'monitor_id': '\\\\?\\DISPLAY#AUS27D2#5&241c4572&0&UID4356#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}'}
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "E:\YouTube - Assetts\OBS PYTHON\zoom_and_follow_mouse.py", line 371, in toggle_zoom
[zoom_and_follow_mouse.py]     def follow(self, mousePos):
[zoom_and_follow_mouse.py]   File "E:\YouTube - Assetts\OBS PYTHON\zoom_and_follow_mouse.py", line 66, in update_source_size
[zoom_and_follow_mouse.py]     ZOOM_DESC_TOG = "Enable/Disable Mouse Zoom"
[zoom_and_follow_mouse.py] KeyError: 'monitor'

Also, sometimes the LINE Numbers do not match up when I open the script inside of Sublime Text. What is the recommended way to make edits and corrections to the script?

Thanks so much for this resource and also for the support.
Joyfully,
Simeon

**Comment by scrubbingmonkey** [comment]
I too have received this error. 
I attempted the solution above but....
Line 227 in the file **zoom_and_follow_mouse.py** has something quite different.

Win 7
OBS 27.2.4
Python 3.6.7

**Comment by ch1ntoo** [comment]
I solved the problem. Try using the latest version of the script with
python 3.10

Thank me later ❤️😊

**Comment by scrubbingmonkey** [comment]
@ch1ntoo 
As I understand it. Since I am using Win 7 that I need to stay below OBS 28 and use ONLY Python 3.6

**Comment by tryptech** [comment]
If this is still an issue, please reproduce and resubmit with current working versions of python, OBS, script and dependencies.
