### ISSUE TITLE
Moves screen but fails to zoom in

### ISSUE THREAD

**Issue by parff9850** [tryptech/obs-zoom-and-follow#8]
Hi there. Looking to make some tutorials but the zoom feature is important to me, this looks great but I'm running into some issues

Python 3.6.8
OBS 26.1.1

Installed the two required modules. Settings show up as expected.

![image](https://user-images.githubusercontent.com/43785354/110170379-20135080-7dc8-11eb-81f6-14cad18b9743.png)

And here it is in use but failing to zoom after resize

![bar](https://user-images.githubusercontent.com/43785354/110170550-5e107480-7dc8-11eb-8ffc-d23de92d9ba0.gif)

Thanks for your efforts

**Comment by isigebengu-mikey** [comment]
You need to go into the transform menu of your display input, and change the **Positional Alignment** to Center and the Bound Box to Stretch to Bounds

![](https://mikey.has-no-bra.in/5cNEKk.png)

**Comment by tryptech** [comment]
@isigebengu-mikey is correct.

Are you still having this issue? @parff9850

**Comment by parff9850** [comment]
> @isigebengu-mikey is correct.
> 
> Are you still having this issue? @parff9850

Will test and update my response. Thanks for the help.

**Comment by tryptech** [comment]
Closing since the script has refactored and dependencies have changed. If the issue comes up again, please create a new issue.
