### ISSUE TITLE
Error when running script - SyntaxError: future feature annotations is not defined

### ISSUE THREAD

**Issue by mitch-webdev** [tryptech/obs-zoom-and-follow#81]
Hello,

I tried to setup your script on my OBS but I get the following error:

I checked that I am running Python 3.6 and I installed pywinctl. Do you know how to fix that?

[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:/Program Files/obs-studio/data/obs-plugins/frontend-tools/scripts\zoom_and_follow_mouse.py", line 21, in <module>
[zoom_and_follow_mouse.py]     import pywinctl as pwc # version >=0.0.38
[zoom_and_follow_mouse.py]   File "C:\Users\info\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinctl\__init__.py", line 4
[zoom_and_follow_mouse.py]     from __future__ import annotations
[zoom_and_follow_mouse.py]     ^
[zoom_and_follow_mouse.py] SyntaxError: future feature annotations is not defined

Thank for your help!

**Comment by MickYayger** [comment]
Hello. The solution is to install an older version of pywinctl.

**Comment by mitch-webdev** [comment]
Hello @MickYayger,

Thank you so much. I installed pywinctl 0.0.38 instead of 0.0.42 and that did the trick! Appreciate your help :)
