### ISSUE TITLE
MacOS - TypeError: tuple indices must be integers or slices, not str

### ISSUE THREAD

**Issue by thomasjguyton** [tryptech/obs-zoom-and-follow#82]
masOS Monterey
Apple M1 Pro

2 monitors, same error with various configurations, including mirroring. Same error when using manual monitor overrides as well. Script is loading but moves surprisingly slow. Any change to the settings takes about 45 seconds to process.

Zoom or Follow function not working at all. Every time I trigger the hotkey, the script log shows the following error:

[zoom_and_follow_mouse.py] Tracking: True
[zoom_and_follow_mouse.py] Source loaded successfully: display_capture
[zoom_and_follow_mouse.py] Source Type: display_capture
[zoom_and_follow_mouse.py] Retrieving monitor 1
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "/Users/tguyton/Documents/OBS/Script downloads/obs-zoom-and-follow-master/zoom_and_follow_mouse.py", line 830, in toggle_zoom
[zoom_and_follow_mouse.py]     zoom.update_source_size()
[zoom_and_follow_mouse.py]   File "/Users/tguyton/Documents/OBS/Script downloads/obs-zoom-and-follow-master/zoom_and_follow_mouse.py", line 295, in update_source_size
[zoom_and_follow_mouse.py]     self.monitor_capture_mac(data)
[zoom_and_follow_mouse.py]   File "/Users/tguyton/Documents/OBS/Script downloads/obs-zoom-and-follow-master/zoom_and_follow_mouse.py", line 159, in monitor_capture_mac
[zoom_and_follow_mouse.py]     if (monitor['id'] == monitor_index):
[zoom_and_follow_mouse.py] TypeError: tuple indices must be integers or slices, not str

Attaching screenshot of script settings in OBS. Using python version 3.10.9.

Any help or insight would be greatly appreciated!
<img width="736" alt="Python   OBS work" src="https://user-images.githubusercontent.com/120826186/208259946-46767bf6-3e97-412a-99c5-5d448b5418b1.png">

**Comment by HeyBradyLang** [comment]
+1, this is happening to me as well.

Mac OS Ventura 13.0.1
OBS 29.0, M1 Macbook Pro.
Python 3.10, Loaded properly.
PyWinCTL 0.0.38

```
[zoom_and_follow_mouse.py] Source loaded successfully: display_capture
[zoom_and_follow_mouse.py] Source Type: display_capture
[zoom_and_follow_mouse.py] Retrieving monitor 1
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "/Users/blang/Downloads/obs-zoom-and-follow-master 3/zoom_and_follow_mouse.py", line 830, in toggle_zoom
[zoom_and_follow_mouse.py]     zoom.update_source_size()
[zoom_and_follow_mouse.py]   File "/Users/blang/Downloads/obs-zoom-and-follow-master 3/zoom_and_follow_mouse.py", line 295, in update_source_size
[zoom_and_follow_mouse.py]     self.monitor_capture_mac(data)
[zoom_and_follow_mouse.py]   File "/Users/blang/Downloads/obs-zoom-and-follow-master 3/zoom_and_follow_mouse.py", line 159, in monitor_capture_mac
[zoom_and_follow_mouse.py]     if (monitor['id'] == monitor_index):
[zoom_and_follow_mouse.py] TypeError: tuple indices must be integers or slices, not str
[zoom_and_follow_mouse.py] Tracking: False
[zoom_and_follow_mouse.py] Source loaded successfully: display_capture
[zoom_and_follow_mouse.py] Source Type: display_capture
[zoom_and_follow_mouse.py] Retrieving monitor 1
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "/Users/blang/Downloads/obs-zoom-and-follow-master 3/zoom_and_follow_mouse.py", line 830, in toggle_zoom
[zoom_and_follow_mouse.py]     zoom.update_source_size()
[zoom_and_follow_mouse.py]   File "/Users/blang/Downloads/obs-zoom-and-follow-master 3/zoom_and_follow_mouse.py", line 295, in update_source_size
[zoom_and_follow_mouse.py]     self.monitor_capture_mac(data)
[zoom_and_follow_mouse.py]   File "/Users/blang/Downloads/obs-zoom-and-follow-master 3/zoom_and_follow_mouse.py", line 159, in monitor_capture_mac
[zoom_and_follow_mouse.py]     if (monitor['id'] == monitor_index):
[zoom_and_follow_mouse.py] TypeError: tuple indices must be integers or slices, not str
[zoom_and_follow_mouse.py] Tracking: True
```

**Comment by nishyp** [comment]
I'm also having the exact same issue as you two!

The script seems to take a toll on my system or has some issues causing momentary freezes/rainbow wheels when first starting and when information is being changed like the Width and Height

System Info:
MacOS Catalina 10.15.7 - 9700k, 64GB RAM, RX 5700 XT
OBS 29.0.0
Python 3.10.9
PyWinCtl 0.0.38

I'm running 3 of the same model Dell Monitors with my system and I've noticed based on what I'm seeing and the screenshot @thomasjguyton provided that the Monitor Override section output is different on MacOS compared to Windows users. 

Examples:
MacOS = Built-In Retina Display: 1728 x 1117
Windows = \\. \DISPLAY1

Could that possibly be the culprit here?

changing 'id' on lines 159 and 160 to 0 seems to make zooming work but I'm not a skilled coder I just did some digging for fun 😅

**Comment by HeyBradyLang** [comment]
Hmm, I'm going to try that too, Nishyp!
Just wanted to add, I also get the rainbow wheel when it starts.

**Comment by nishyp** [comment]
After some further digging, I'm getting mouse position figures to change in the log when I have my mouse pointer on a different monitor but it does not follow, I've toggled Tracking to True and False to confirm that this is the case.

When activating zoom I'm having the same issue as #87 
Where the zoom always seems to go to the upper corner no matter where the mouse starts, not following the movement or position of the mouse and it stays there until the hotkey is pressed to zoom out.
I also agree that the documentation needs to be cleared up in regard to the Bounding Box Type choice

**Comment by DeysonOrtiz** [comment]
I am getting the same error on a Mac Laptop with no connected monitors.
] TypeError: tuple indices must be integers or slices, not str

OBS 29.02 Macbook Pro.
Python 3.10, Loaded.
PyWinCTL 0.0.38

Please advice. 🙂
Thank you and have a Fantastic Day! 🙂

**Comment by tryptech** [comment]
I'm going to continue working on all Mac related issues in https://github.com/tryptech/obs-zoom-and-follow/issues/97 so I will close this for now. Please put any notes, issues, observations, etc. in that issue.
