### ISSUE TITLE
I don't see the "Python Settings" tab in OBS Studio 28.1.2 (64 bit) on Linux Mint 20.3 Cinnamon

### ISSUE THREAD

**Issue by Raytle** [tryptech/obs-zoom-and-follow#84]
I read...

> Make sure that you configure the correct version of Python within OBS in the "Scripts" window > "Python Settings" tab

... but I don't see "Python Settings" tab

![2022-12-21_05-09](https://user-images.githubusercontent.com/81956552/208912975-449b1f6b-7d80-4c75-a957-c80170ca7c9b.png)

What should I do?

In case it matters, I copied and pasted the following from the "Script Log."...

```
File "/home/y/zoom_and_follow_mouse.py", line 8
[zoom_and_follow_mouse.py]     <!DOCTYPE html>
[zoom_and_follow_mouse.py]     ^
[zoom_and_follow_mouse.py] SyntaxError: invalid syntax
```

and I confirmed that PyWinCtl is installed...

```
Name: PyWinCtl
Version: 0.0.42
Summary: Cross-Platform toolkit to get info on and control windows on screen
Home-page: https://github.com/Kalmat/PyWinCtl
Author: Kalmat
Author-email: palookjones@gmail.com
License: BSD 3
Location: /home/y/.local/lib/python3.8/site-packages
Requires: ewmh, xlib, PyRect
Required-by:
```

**Comment by Xechorizo** [comment]
Had this same problem - the download is providing an XML metadata instead of the python script. Try viewing it raw and pasting its contents into a .py file.

**Comment by Raytle** [comment]
Thanks for letting me know. I appreciate that. I found a similar solution in ffmpeg...

```
ffmpeg -f x11grab -follow_mouse centered -framerate 25 -video_size cif -i :0.0 -preset slow output.mkv
```

I'd like to find a way to follow the caret (the "text cursor") just as I can now follow the mouse. Do you know of a way to do that?

**Comment by tryptech** [comment]
If this is still an issue, please reproduce and resubmit with current working versions of python, OBS, script and dependencies.
