### ISSUE TITLE
Everytime I try to load up the script I get this error:

### ISSUE THREAD

**Issue by WilvliW** [tryptech/obs-zoom-and-follow#85]
Is it cause im using pip version 18.1? i've tried upgrading using the command but it doesnt work.

[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:/Program Files/obs-studio/data/obs-plugins/frontend-tools/scripts\zoom_and_follow_mouse.py", line 21, in <module>
[zoom_and_follow_mouse.py]     import pywinctl as pwc # version >=0.0.38
[zoom_and_follow_mouse.py]   File "C:\Users\Will\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinctl\__init__.py", line 4
[zoom_and_follow_mouse.py]     from __future__ import annotations
[zoom_and_follow_mouse.py]     ^
[zoom_and_follow_mouse.py] SyntaxError: future feature annotations is not defined
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:/Program Files/obs-studio/data/obs-plugins/frontend-tools/scripts\zoom_and_follow_mouse.py", line 21, in <module>
[zoom_and_follow_mouse.py]     import pywinctl as pwc # version >=0.0.38
[zoom_and_follow_mouse.py]   File "C:\Users\Will\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinctl\__init__.py", line 4
[zoom_and_follow_mouse.py]     from __future__ import annotations
[zoom_and_follow_mouse.py]     ^
[zoom_and_follow_mouse.py] SyntaxError: future feature annotations is not defined

**Comment by Xechorizo** [comment]
Wrong version of Python from the look o fit

**Comment by maximillionfrday** [comment]
agreed... please see youtube video in this comment..  It worked for me.  https://github.com/tryptech/obs-zoom-and-follow/issues/92#issuecomment-1411442158
