### ISSUE TITLE
Not working properly with OBS 29.0.0 on Windows 11 (Python 3.10)

### ISSUE THREAD

**Issue by kumueric** [tryptech/obs-zoom-and-follow#87]
Hi,
Sorry to report that something is not quite right with the script v.2022.10.21 and OBS 29.0.0 on Windows 11 with Python 3.10.

Please also clarify the bullet #5 under "How to Use."  The instruction says, "**Stretch** to inner bounds," but on OBS 29.0.0, the choices are

- No bounds
- **Stretch** to bounds
- **Scale** to inner bounds
- Scale to outer bounds
- Scale to width of bounds
- Scale to height of bounds
- Maximum size only

Do you mean "**Scale** to inner bounds" (instead of "**Stretch** to inner bounds")?

I tried "No bounds," "Stretch to bounds," and "Scale to inner bounds," but I could not get it to work.  The zoom always seems to go to the upper corner no matter where the mouse starts.

Thank you for your help!

**Comment by Ion3** [comment]
Hi,

I have the same issues using Python 3.10 on Windows 11 with OBS 29.0.0. I downloaded the obs-zoom-and-follow script on 13.Jan.2023 as a ZIP file. My script log looks like this: 

```
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:\Program Files/obs-studio/data/obs-plugins/frontend-tools/scripts/obs-zoom-and-follow-master\zoom_and_follow_mouse.py", line 21, in <module>
[zoom_and_follow_mouse.py]     import pywinctl as pwc # version >=0.0.38
[zoom_and_follow_mouse.py]   File "C:\Users\Timo\AppData\Local\Programs\Python\Python310\lib\site-packages\pywinctl\__init__.py", line 775, in <module>
[zoom_and_follow_mouse.py]     from ._pywinctl_win import (Win32Window as Window, checkPermissions, getActiveWindow, getActiveWindowTitle,
[zoom_and_follow_mouse.py]   File "C:\Users\Timo\AppData\Local\Programs\Python\Python310\lib\site-packages\pywinctl\_pywinctl_win.py", line 25, in <module>
[zoom_and_follow_mouse.py]     import win32api
[zoom_and_follow_mouse.py] ModuleNotFoundError: No module named 'win32api'
```

Is somebody able to help? Thank you.

**Comment by Riscon** [comment]
Windows 11 22H2 (Build 22621.1413)
OBS Version 29.0.2 (64-bit, windows)
Python Version 3.10.10
Script Version v.2023.02.13

Currently not working as intended. The zoom always seems to go to the upper corner no matter where the mouse starts.
Also the zoom does not follow the mouse around.

Exactly the same configuration running on Windows 10 22H2 (Build 19045.2788) works perfectly fine.

**Comment by tryptech** [comment]
If this is still an issue, please reproduce and resubmit with current working versions of python, OBS, script and dependencies.
