### ISSUE TITLE
Error while loading script : zoom_and_follow.py

### ISSUE THREAD

**Issue by kocharee** [tryptech/obs-zoom-and-follow#88]
**Below error is displayed while loading "zoom_and_follow.py" script:**

[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:/Program Files/obs-studio/data/obs-plugins/frontend-tools/scripts\zoom_and_follow_mouse.py", line 21, in <module>
[zoom_and_follow_mouse.py]     import pywinctl as pwc # version >=0.0.38
[zoom_and_follow_mouse.py]   File "C:\Users\XXXX\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinctl\__init__.py", line 4
[zoom_and_follow_mouse.py]     from __future__ import annotations
[zoom_and_follow_mouse.py]     ^
[zoom_and_follow_mouse.py] SyntaxError: future feature annotations is not defined

**Comment by MariMakes** [comment]
Hey @kocharee,

I encountered the same just now. 
But found this https://github.com/tryptech/obs-zoom-and-follow/issues/81 issue mentioning you need an older version.

I reinstalled a new version like this
`pip install --force-reinstall -v "pywinctl==0.0.38"`

and now it seems to work.
Good luck 💪

**Comment by DureSabih** [comment]
Will try this now thanks 

> pip install --force-reinstall -v "pywinctl==0.0.38"

**Comment by DureSabih** [comment]
> Hey @kocharee,
> 
> I encountered the same just now. But found this #81 issue mentioning you need an older version.
> 
> I reinstalled a new version like this `pip install --force-reinstall -v "pywinctl==0.0.38"`
> 
> and now it seems to work. Good luck 💪

this isnt working for me.  giving more erros 
[zoom_and_follow_mouse.py] ModuleNotFoundError: No module named 'win32api'

**Comment by tryptech** [comment]
Closing as python installation errors are out of scope for support.
