### ISSUE TITLE
Error Initially Loading Script

### ISSUE THREAD

**Issue by donovankean** [tryptech/obs-zoom-and-follow#92]
After installing python 3.6.8, linking OBS to it, and installing the PyWinCtl, I then try to add the script and get this message. Any ideas on how to fix it? Thanks in advance!

For context I'm running OBS v29.0.0, the latest Windows 11 build, and a 3840x2160 144hz monitor. 

[Script Log]
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:/Users/Donovan/Desktop\zoom_and_follow_mouse.py", line 21, in <module>
[zoom_and_follow_mouse.py]     import pywinctl as pwc # version >=0.0.38
[zoom_and_follow_mouse.py]   File "C:\Users\Donovan\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinctl\__init__.py", line 4
[zoom_and_follow_mouse.py]     from __future__ import annotations
[zoom_and_follow_mouse.py]     ^
[zoom_and_follow_mouse.py] SyntaxError: future feature annotations is not defined

**Comment by maximillionfrday** [comment]
i had the same issue.  here is an entry that has a youtube video that got me sorted out 
https://obsproject.com/forum/threads/zoom-and-follow.127743/post-601033

**Comment by donovankean** [comment]
> i had the same issue. here is an entry that has a youtube video that got me sorted out https://obsproject.com/forum/threads/zoom-and-follow.127743/post-601033

Thanks! This solved my problem. Although, for some reason when I zoom it now goes to the upper left hand corner of my OBS canvas. Any ideas?

![image](https://user-images.githubusercontent.com/123996167/216075384-71f20b95-0783-45d1-9bdf-e378c009ca7f.png)

**Comment by connorferster** [comment]
If you have not solved this yet, you can see this tutorial: https://www.youtube.com/watch?v=OUyPpol0yYo

**Comment by donovankean** [comment]
> If you have not solved this yet, you can see this tutorial: https://www.youtube.com/watch?v=OUyPpol0yYo

Awesome thanks! I anctually ended up getting it fixed. Turns out, I just needed to edit the transform settings on the video source. I think it was just a scale to fit setting or something.
