### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by wrexik** [tryptech/obs-zoom-and-follow#94]
Can you add option to just enable all the time? For one source?

**Comment by nishyp** [comment]
It's activated and deactivated with hotkeys so should stay enabled until you disable it?

**Comment by wrexik** [comment]
Yeah thanks, i added multifunction to my streamdeck

**Comment by tryptech** [comment]
If this is still an issue, please reproduce and resubmit with current working versions of python, OBS, script and dependencies.
