### ISSUE TITLE
I keep getting this IndexError

### ISSUE THREAD

**Issue by rk3773** [tryptech/obs-zoom-and-follow#98]
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "G:\OBS\obs-studio 29\OBS PYTHON\zoom_and_follow_mouse.py", line 371, in toggle_zoom
[zoom_and_follow_mouse.py]     zoom.update_source_size()
[zoom_and_follow_mouse.py]   File "G:\OBS\obs-studio 29\OBS PYTHON\zoom_and_follow_mouse.py", line 58, in update_source_size
[zoom_and_follow_mouse.py]     window = pwc.getWindowsWithTitle(data[0])[0]
[zoom_and_follow_mouse.py] IndexError: list index out of range

**Comment by rk3773** [comment]
Figured it out

**Comment by fsufan2003** [comment]
What was the solution.  I am dying over here
