### ISSUE TITLE
script not working

### ISSUE THREAD

**Issue by TheGamersCubeNL** [tryptech/obs-zoom-and-follow#99]
error

[zoom_and_follow_mouse.py] {'monitor_id': '\\\\?\\DISPLAY#BNQ78E4#5&396a6378&0&UID4352#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}'}
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "D:\OBS PYTHON\zoom_and_follow_mouse.py", line 371, in toggle_zoom
[zoom_and_follow_mouse.py]     zoom.update_source_size()
[zoom_and_follow_mouse.py]   File "D:\OBS PYTHON\zoom_and_follow_mouse.py", line 66, in update_source_size
[zoom_and_follow_mouse.py]     data = loads(data)['monitor']
[zoom_and_follow_mouse.py] KeyError: 'monitor'

**Comment by SlightlyWilson** [comment]
I'm getting the same Error currently

**Comment by hernancasillas** [comment]
Same here

**Comment by chuthehuan** [comment]
i use portable python 3.6 with 28.1.2 and it works well. Both display capture and window capture. You should give it a try!

**Comment by chuthehuan** [comment]
if you did not use installer version, you can simply download [OBS-Studio-28.1.2-Full-x64.zip](https://github.com/obsproject/obs-studio/releases/download/28.1.2/OBS-Studio-28.1.2-Full-x64.zip) , unzip and run it, old preferences and scripts are preserved as normal.

**Comment by tryptech** [comment]
If this is still an issue, please reproduce and resubmit with current working versions of python, OBS, script and dependencies.
